In [1]:
import scanpy as sc
data_dir = '../../dataset/Marshall2022High_mouse_sampled.h5ad'
adata = sc.read_h5ad(data_dir)

In [2]:
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)

In [3]:

adata.var['gene_id'] = adata.var.index
adata.var.index = adata.var['gene_name']

# 输出 adata.var
adata.var

,feature_is_filtered,feature_reference,feature_biotype,feature_name-0,feature_length-0,feature_type-0,feature_name-1,feature_length-1,feature_type-1,feature_name-2,...,feature_length-5,feature_type-5,feature_name-6,feature_length-6,feature_type-6,feature_name-7,feature_length-7,feature_type-7,gene_name,gene_id
gene_name,,,,,,,,,,,,,,,,,,,,,
Erg28,False,NCBITaxon:10090,gene,Erg28,696,protein_coding,Erg28,696,protein_coding,Erg28,...,696,protein_coding,Erg28,696,protein_coding,Erg28,696,protein_coding,Erg28,ENSMUSG00000021252
0610009B22Rik,False,NCBITaxon:10090,gene,0610009B22Rik,852,protein_coding,0610009B22Rik,852,protein_coding,0610009B22Rik,...,852,protein_coding,0610009B22Rik,852,protein_coding,0610009B22Rik,852,protein_coding,0610009B22Rik,ENSMUSG00000007777
0610009E02Rik,False,NCBITaxon:10090,gene,0610009E02Rik,981,lncRNA,0610009E02Rik,981,lncRNA,0610009E02Rik,...,981,lncRNA,0610009E02Rik,981,lncRNA,0610009E02Rik,981,lncRNA,0610009E02Rik,ENSMUSG00000086714
0610009L18Rik,False,NCBITaxon:10090,gene,0610009L18Rik,639,lncRNA,0610009L18Rik,639,lncRNA,0610009L18Rik,...,639,lncRNA,0610009L18Rik,639,lncRNA,0610009L18Rik,639,lncRNA,0610009L18Rik,ENSMUSG00000043644
Dele1,False,NCBITaxon:10090,gene,Dele1,2394,protein_coding,Dele1,2394,protein_coding,Dele1,...,2394,protein_coding,Dele1,2394,protein_coding,Dele1,2394,protein_coding,Dele1,ENSMUSG00000024442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mt-Tm,False,NCBITaxon:10090,gene,mt-Tm,69,Mt_tRNA,mt-Tm,69,Mt_tRNA,mt-Tm,...,69,Mt_tRNA,mt-Tm,69,Mt_tRNA,mt-Tm,69,Mt_tRNA,mt-Tm,ENSMUSG00000064344
mt-Tp,False,NCBITaxon:10090,gene,mt-Tp,67,Mt_tRNA,mt-Tp,67,Mt_tRNA,mt-Tp,...,67,Mt_tRNA,mt-Tp,67,Mt_tRNA,mt-Tp,67,Mt_tRNA,mt-Tp,ENSMUSG00000064372
mt-Tq,False,NCBITaxon:10090,gene,mt-Tq,71,Mt_tRNA,mt-Tq,71,Mt_tRNA,mt-Tq,...,71,Mt_tRNA,mt-Tq,71,Mt_tRNA,mt-Tq,71,Mt_tRNA,mt-Tq,ENSMUSG00000064343
mt-Tt,False,NCBITaxon:10090,gene,mt-Tt,67,Mt_tRNA,mt-Tt,67,Mt_tRNA,mt-Tt,...,67,Mt_tRNA,mt-Tt,67,Mt_tRNA,mt-Tt,67,Mt_tRNA,mt-Tt,ENSMUSG00000064371
mt-Tv,False,NCBITaxon:10090,gene,mt-Tv,69,Mt_tRNA,mt-Tv,69,Mt_tRNA,mt-Tv,...,69,Mt_tRNA,mt-Tv,69,Mt_tRNA,mt-Tv,69,Mt_tRNA,mt-Tv,ENSMUSG00000064338

In [4]:
import pandas as pd
var_df = pd.read_parquet('../../sc_pretrained/var.parquet')
var_df

            feature_id feature_name
0      ENSG00000186092        OR4F5
1      ENSG00000284733       OR4F29
2      ENSG00000284662       OR4F16
3      ENSG00000187634       SAMD11
4      ENSG00000188976        NOC2L
...                ...          ...
19326  ENSG00000288702       UGT1A3
19327  ENSG00000288705       UGT1A5
19328  ENSG00000182484       WASH6P
19329  ENSG00000288622   PDCD6-AHRR
19330  ENSG00000285815  GET1-SH3BGR

[19331 rows x 2 columns]

In [5]:
all_genes = var_df['feature_name'].tolist()
all_genes

['OR4F5',
 'OR4F29',
 'OR4F16',
 'SAMD11',
 'NOC2L',
 'KLHL17',
 'PLEKHN1',
 'PERM1',
 'HES4',
 'ISG15',
 'AGRN',
 'RNF223',
 'C1orf159',
 'TTLL10',
 'TNFRSF18',
 'TNFRSF4',
 'SDF4',
 'B3GALT6',
 'C1QTNF12',
 'UBE2J2',
 'SCNN1D',
 'ACAP3',
 'PUSL1',
 'INTS11',
 'CPTP',
 'TAS1R3',
 'DVL1',
 'MXRA8',
 'AURKAIP1',
 'CCNL2',
 'MRPL20',
 'ANKRD65',
 'TMEM88B',
 'VWA1',
 'ATAD3C',
 'ATAD3B',
 'ATAD3A',
 'TMEM240',
 'SSU72',
 'FNDC10',
 'MIB2',
 'MMP23B',
 'CDK11B',
 'SLC35E2B',
 'CDK11A',
 'NADK',
 'GNB1',
 'CALML6',
 'TMEM52',
 'CFAP74',
 'GABRD',
 'PRKCZ',
 'FAAP20',
 'SKI',
 'MORN1',
 'RER1',
 'PEX10',
 'PLCH2',
 'PANK4',
 'HES5',
 'TNFRSF14',
 'PRXL2B',
 'MMEL1',
 'TTC34',
 'ACTRT2',
 'PRDM16',
 'ARHGEF16',
 'MEGF6',
 'TPRG1L',
 'WRAP73',
 'TP73',
 'CCDC27',
 'SMIM1',
 'LRRC47',
 'CEP104',
 'DFFB',
 'C1orf174',
 'AJAP1',
 'NPHP4',
 'KCNAB2',
 'CHD5',
 'RPL22',
 'RNF207',
 'ICMT',
 'HES3',
 'GPR153',
 'ACOT7',
 'HES2',
 'ESPN',
 'TNFRSF25',
 'PLEKHG5',
 'NOL9',
 'TAS1R1',
 'ZBTB48',
 'KLHL21',
 'PHF13',
 'THAP3',
 'DNAJC11',
 'CAMTA1',
 'VAMP3',
 'PER3',
 'UTS2',
 'TNFRSF9',
 'PARK7',
 'ERRFI1',
 'SLC45A1',
 'RERE',
 'ENO1',
 'CA6',
 'SLC2A7',
 'SLC2A5',
 'GPR157',
 'H6PD',
 'SPSB1',
 'SLC25A33',
 'TMEM201',
 'PIK3CD',
 'CLSTN1',
 'CTNNBIP1',
 'LZIC',
 'NMNAT1',
 'RBP7',
 'UBE4B',
 'KIF1B',
 'PGD',
 'CENPS',
 'CORT',
 'DFFA',
 'PEX14',
 'CASZ1',
 'C1orf127',
 'TARDBP',
 'MASP2',
 'SRM',
 'EXOSC10',
 'MTOR',
 'ANGPTL7',
 'UBIAD1',
 'DISP3',
 'FBXO2',
 'FBXO44',
 'FBXO6',
 'MAD2L2',
 'DRAXIN',
 'AGTRAP',
 'C1orf167',
 'MTHFR',
 'CLCN6',
 'NPPA',
 'NPPB',
 'KIAA2013',
 'PLOD1',
 'MFN2',
 'MIIP',
 'TNFRSF8',
 'TNFRSF1B',
 'VPS13D',
 'DHRS3',
 'AADACL4',
 'AADACL3',
 'C1orf158',
 'PRAMEF12',
 'PRAMEF1',
 'PRAMEF11',
 'HNRNPCL1',
 'PRAMEF2',
 'PRAMEF4',
 'PRAMEF10',
 'PRAMEF7',
 'PRAMEF6',
 'PRAMEF27',
 'HNRNPCL3',
 'PRAMEF25',
 'HNRNPCL2',
 'PRAMEF26',
 'HNRNPCL4',
 'PRAMEF9',
 'PRAMEF13',
 'PRAMEF18',
 'PRAMEF5',
 'PRAMEF8',
 'PRAMEF33',
 'PRAMEF15',
 'PRAMEF14',
 'PRAMEF19',
 'PRAMEF17',
 'PRAMEF20',
 'LRRC38',
 'PDPN',
 'PRDM2',
 'KAZN',
 'TMEM51',
 'FHAD1',
 'EFHD2',
 'CTRC',
 'CELA2A',
 'CELA2B',
 'CASP9',
 'DNAJC16',
 'AGMAT',
 'DDI2',
 'RSC1A1',
 'PLEKHM2',
 'SLC25A34',
 'TMEM82',
 'FBLIM1',
 'UQCRHL',
 'SPEN',
 'ZBTB17',
 'SRARP',
 'HSPB7',
 'CLCNKA',
 'CLCNKB',
 'FAM131C',
 'EPHA2',
 'ARHGEF19',
 'CPLANE2',
 'FBXO42',
 'SZRD1',
 'SPATA21',
 'NECAP2',
 'NBPF1',
 'CROCC',
 'MFAP2',
 'ATP13A2',
 'SDHB',
 'PADI2',
 'PADI1',
 'PADI3',
 'PADI4',
 'PADI6',
 'RCC2',
 'ARHGEF10L',
 'ACTL8',
 'IGSF21',
 'KLHDC7A',
 'PAX7',
 'TAS1R2',
 'ALDH4A1',
 'IFFO2',
 'UBR4',
 'EMC1',
 'MRTO4',
 'AKR7A3',
 'AKR7A2',
 'SLC66A1',
 'CAPZB',
 'MICOS10',
 'NBL1',
 'HTR6',
 'TMCO4',
 'RNF186',
 'OTUD3',
 'PLA2G2E',
 'PLA2G2A',
 'PLA2G5',
 'PLA2G2D',
 'PLA2G2F',
 'PLA2G2C',
 'UBXN10',
 'VWA5B1',
 'CAMK2N1',
 'MUL1',
 'FAM43B',
 'CDA',
 'PINK1',
 'DDOST',
 'KIF17',
 'SH2D5',
 'HP1BP3',
 'EIF4G3',
 'ECE1',
 'NBPF3',
 'ALPL',
 'RAP1GAP',
 'USP48',
 'LDLRAD2',
 'HSPG2',
 'CELA3B',
 'CELA3A',
 'CDC42',
 'WNT4',
 'ZBTB40',
 'EPHA8',
 'C1QA',
 'C1QC',
 'C1QB',
 'EPHB2',
 'LACTBL1',
 'TEX46',
 'KDM1A',
 'LUZP1',
 'HTR1D',
 'HNRNPR',
 'ZNF436',
 'TCEA3',
 'ASAP3',
 'E2F2',
 'ID3',
 'RPL11',
 'ELOA',
 'PITHD1',
 'LYPLA2',
 'GALE',
 'HMGCL',
 'FUCA1',
 'CNR2',
 'PNRC2',
 'SRSF10',
 'MYOM3',
 'IL22RA1',
 'IFNLR1',
 'GRHL3',
 'STPG1',
 'NIPAL3',
 'RCAN3',
 'NCMAP',
 'SRRM1',
 'CLIC4',
 'RUNX3',
 'SYF2',
 'RSRP1',
 'RHD',
 'TMEM50A',
 'RHCE',
 'MACO1',
 'LDLRAP1',
 'MAN1C1',
 'SELENON',
 'MTFR1L',
 'AUNIP',
 'PAQR7',
 'STMN1',
 'PAFAH2',
 'EXTL1',
 'SLC30A2',
 'TRIM63',
 'PDIK1L',
 'FAM110D',
 'C1orf232',
 'ZNF593OS',
 'ZNF593',
 'CNKSR1',
 'CATSPER4',
 'CEP85',
 'SH3BGRL3',
 'UBXN11',
 'CD52',
 'CRYBG2',
 'ZNF683',
 'LIN28A',
 'DHDDS',
 'HMGN2',
 'RPS6KA1',
 'ARID1A',
 'PIGV',
 'ZDHHC18',
 'SFN',
 'GPN2',
 'GPATCH3',
 'NUDC',
 'NR0B2',
 'KDF1',
 'TRNP1',
 'TENT5B',
 'SLC9A1',
 'WDTC1',
 'TMEM222',
 'SYTL1',
 'MAP3K6',
 'FCN3',
 'CD164L2',
 'GPR3',
 'WASF2',
 'AHDC1',
 'FGR',
 'IFI6',
 'FAM76A',
 'STX12',
 'PPP1R8',
 'THEMIS2',
 'RPA2',
 'SMPDL3B',
 'XKR8',
 'EYA3',
 'PTAFR',
 'DNAJC8',
 'ATP5IF1',
 'SESN2',
 'MED18',
 'PHACTR4',
 'RCC1',
 'TRNAU1AP',
 'TAF12',
 'RAB42',
 'GMEB1',
 'YTHDF2',
 'OPRD1',
 'EPB41',
 'TMEM200B',
 'SRSF4',
 'MECR',
 'PTPRU',
 'MATN1',
 'LAPTM5',
 'SDC3',
 'PUM1',
 'NKAIN1',
 'SNRNP40',
 'ZCCHC17',
 'FABP3',
 'SERINC2',
 'TINAGL1',
 'HCRTR1',
 'PEF1',
 'COL16A1',
 'ADGRB2',
 'SPOCD1',
 'PTP4A2',
 'KHDRBS1',
 'TMEM39B',
 'KPNA6',
 'TXLNA',
 'CCDC28B',
 'IQCC',
 'DCDC2B',
 'TMEM234',
 'EIF3I',
 'FAM167B',
 'LCK',
 'HDAC1',
 'MARCKSL1',
 'TSSK3',
 'FAM229A',
 'BSDC1',
 'ZBTB8B',
 'ZBTB8A',
 'ZBTB8OS',
 'RBBP4',
 'SYNC',
 'KIAA1522',
 'YARS1',
 'S100PBP',
 'FNDC5',
 'HPCA',
 'TMEM54',
 'RNF19B',
 'AK2',
 'AZIN2',
 'TRIM62',
 'ZNF362',
 'A3GALT2',
 'PHC2',
 'ZSCAN20',
 'CSMD2',
 'HMGB4',
 'C1orf94',
 'SMIM12',
 'GJB5',
 'GJB4',
 'GJB3',
 'GJA4',
 'DLGAP3',
 'TMEM35B',
 'ZMYM6',
 'ZMYM1',
 'SFPQ',
 'ZMYM4',
 'KIAA0319L',
 'NCDN',
 'TFAP2E',
 'PSMB2',
 'C1orf216',
 'CLSPN',
 'AGO4',
 'AGO1',
 'AGO3',
 'TEKT2',
 'ADPRS',
 'COL8A2',
 'TRAPPC3',
 'MAP7D1',
 'THRAP3',
 'SH3D21',
 'EVA1B',
 'STK40',
 'LSM10',
 'OSCP1',
 'MRPS15',
 'CSF3R',
 'GRIK3',
 'ZC3H12A',
 'MEAF6',
 'SNIP1',
 'DNALI1',
 'GNL2',
 'RSPO1',
 'C1orf109',
 'CDCA8',
 'EPHA10',
 'MANEAL',
 'YRDC',
 'C1orf122',
 'MTF1',
 'INPP5B',
 'SF3A3',
 'FHL3',
 'UTP11',
 'POU3F1',
 'RRAGC',
 'MYCBP',
 'GJA9',
 'RHBDL2',
 'AKIRIN1',
 'NDUFS5',
 'MACF1',
 'BMP8A',
 'PABPC4',
 'HEYL',
 'NT5C1A',
 'HPCAL4',
 'PPIE',
 'BMP8B',
 'OXCT2',
 'TRIT1',
 'MYCL',
 'MFSD2A',
 'CAP1',
 'PPT1',
 'RLF',
 'TMCO2',
 'ZMPSTE24',
 'COL9A2',
 'SMAP2',
 'ZFP69B',
 'ZFP69',
 'EXO5',
 'ZNF684',
 'RIMS3',
 'NFYC',
 'KCNQ4',
 'CITED4',
 'CTPS1',
 'SLFNL1',
 'SCMH1',
 'FOXO6',
 'EDN2',
 'HIVEP3',
 'GUCA2B',
 'GUCA2A',
 'FOXJ3',
 'RIMKLA',
 'ZMYND12',
 'PPCS',
 'CCDC30',
 'PPIH',
 'YBX1',
 'CLDN19',
 'P3H1',
 'C1orf50',
 'TMEM269',
 'SVBP',
 'ERMAP',
 'ZNF691',
 'SLC2A1',
 'FAM183A',
 'EBNA1BP2',
 'CFAP57',
 'TMEM125',
 'C1orf210',
 'TIE1',
 'MPL',
 'CDC20',
 'ELOVL1',
 'MED8',
 'SZT2',
 'HYI',
 'PTPRF',
 'KDM4A',
 'ST3GAL3',
 'ARTN',
 'IPO13',
 'DPH2',
 'ATP6V0B',
 'B4GALT2',
 'CCDC24',
 'SLC6A9',
 'KLF17',
 'KLF18',
 'DMAP1',
 'ERI3',
 'RNF220',
 'TMEM53',
 'ARMH1',
 'KIF2C',
 'RPS8',
 'BEST4',
 'PLK3',
 'DYNLT4',
 'BTBD19',
 'PTCH2',
 'EIF2B3',
 'HECTD3',
 'UROD',
 'ZSWIM5',
 'HPDL',
 'MUTYH',
 'TOE1',
 'TESK2',
 'CCDC163',
 'MMACHC',
 'PRDX1',
 'AKR1A1',
 'NASP',
 'CCDC17',
 'GPBP1L1',
 'TMEM69',
 'IPP',
 'MAST2',
 'PIK3R3',
 'TSPAN1',
 'P3R3URF',
 'POMGNT1',
 'LURAP1',
 'RAD54L',
 'LRRC41',
 'UQCRH',
 'NSUN4',
 'FAAH',
 'DMBX1',
 'TMEM275',
 'KNCN',
 'MKNK1',
 'MOB3C',
 'ATPAF1',
 'TEX38',
 'EFCAB14',
 'CYP4B1',
 'CYP4A11',
 'CYP4X1',
 'CYP4Z1',
 'CYP4A22',
 'PDZK1IP1',
 'TAL1',
 'STIL',
 'CMPK1',
 'FOXE3',
 'FOXD2',
 'TRABD2B',
 'SLC5A9',
 'SPATA6',
 'AGBL4',
 'BEND5',
 'ELAVL4',
 'DMRTA2',
 'FAF1',
 'CDKN2C',
 'C1orf185',
 'RNF11',
 'TTC39A',
 'EPS15',
 'OSBPL9',
 'NRDC',
 'RAB3B',
 'TXNDC12',
 'KTI12',
 'BTF3L4',
 'ZFYVE9',
 'CC2D1B',
 'ORC1',
 'PRPF38A',
 'TUT4',
 'GPX7',
 'SHISAL2A',
 'COA7',
 'ZYG11B',
 'ZYG11A',
 'ECHDC2',
 'SCP2',
 'PODN',
 'SLC1A7',
 'CPT2',
 'CZIB',
 'MAGOH',
 'LRP8',
 'DMRTB1',
 'GLIS1',
 'NDC1',
 'YIPF1',
 'DIO1',
 'HSPB11',
 'LRRC42',
 'LDLRAD1',
 'TMEM59',
 'TCEANC2',
 'CDCP2',
 'CYB5RL',
 'MRPL37',
 'SSBP3',
 'ACOT11',
 'FAM151A',
 'MROH7',
 'TTC4',
 'PARS2',
 'TTC22',
 'LEXM',
 'DHCR24',
 'TMEM61',
 'BSND',
 'PCSK9',
 'USP24',
 'PLPP3',
 'PRKAA2',
 'FYB2',
 'C8A',
 'C8B',
 'DAB1',
 'OMA1',
 'TACSTD2',
 'MYSM1',
 'JUN',
 'FGGY',
 'HOOK1',
 'CYP2J2',
 'C1orf87',
 'NFIA',
 'TM2D1',
 'PATJ',
 'L1TD1',
 'KANK4',
 'USP1',
 'DOCK7',
 'ANGPTL3',
 'ATG4C',
 'FOXD3',
 'ALG6',
 'ITGB3BP',
 'EFCAB7',
 'PGM1',
 'ROR1',
 'UBE2U',
 'CACHD1',
 'RAVER2',
 'JAK1',
 'AK4',
 'DNAJC6',
 'LEPROT',
 'LEPR',
 'PDE4B',
 'SGIP1',
 'DYNLT5',
 'INSL5',
 'DNAI4',
 'MIER1',
 'SLC35D1',
 'C1orf141',
 'IL23R',
 'IL12RB2',
 'SERBP1',
 'GADD45A',
 'GNG12',
 'DIRAS3',
 'WLS',
 'RPE65',
 'DEPDC1',
 'LRRC7',
 'LRRC40',
 'SRSF11',
 'ANKRD13C',
 'CTH',
 'PTGER3',
 'ZRANB2',
 'NEGR1',
 'LRRIQ3',
 'FPGT',
 'TNNI3K',
 'LRRC53',
 'ERICH3',
 'CRYZ',
 'TYW3',
 'LHX8',
 'SLC44A5',
 'ACADM',
 'RABGGTB',
 'MSH4',
 'ASB17',
 'ST6GALNAC3',
 'ST6GALNAC5',
 'PIGK',
 'AK5',
 'ZZZ3',
 'USP33',
 'MIGA1',
 'NEXN',
 'FUBP1',
 'DNAJB4',
 'GIPC2',
 'PTGFR',
 'IFI44L',
 'IFI44',
 'ADGRL4',
 'ADGRL2',
 'TTLL7',
 'PRKACB',
 'SAMD13',
 'DNASE2B',
 'RPF1',
 'GNG5',
 'SPATA1',
 'CTBS',
 'SSX2IP',
 'LPAR3',
 'MCOLN2',
 'DNAI3',
 'MCOLN3',
 'SYDE2',
 'C1orf52',
 'BCL10',
 'DDAH1',
 'CCN1',
 'ZNHIT6',
 'COL24A1',
 'ODF2L',
 'CLCA2',
 'CLCA1',
 'CLCA4',
 'SH3GLB1',
 'SELENOF',
 'HS2ST1',
 'LMO4',
 'PKN2',
 'GTF2B',
 'KYAT3',
 'RBMXL1',
 'GBP3',
 'GBP1',
 'GBP2',
 'GBP7',
 'GBP4',
 'GBP5',
 'GBP6',
 'LRRC8B',
 'LRRC8C',
 'LRRC8D',
 'ZNF326',
 'BARHL2',
 'ZNF644',
 'HFM1',
 'CDC7',
 'TGFBR3',
 'BRDT',
 'EPHX4',
 'SETSIP',
 'BTBD8',
 'C1orf146',
 'GLMN',
 'RPAP2',
 'GFI1',
 'EVI5',
 'RPL5',
 'DIPK1A',
 'MTF2',
 'TMED5',
 'CCDC18',
 'DR1',
 'FNBP1L',
 'BCAR3',
 'DNTTIP2',
 'GCLM',
 'ABCA4',
 'ARHGAP29',
 'ABCD3',
 'F3',
 'SLC44A3',
 'CNN3',
 'ALG14',
 'TLCD4',
 'RWDD3',
 'PTBP2',
 'DPYD',
 'SNX7',
 'PLPPR5',
 'PLPPR4',
 'PALMD',
 'FRRS1',
 'AGL',
 'SLC35A3',
 'MFSD14A',
 'SASS6',
 'TRMT13',
 'LRRC39',
 'DBT',
 'RTCA',
 'CDC14A',
 'GPR88',
 'VCAM1',
 'EXTL2',
 'SLC30A7',
 'DPH5',
 'S1PR1',
 'OLFM3',
 'COL11A1',
 'RNPC3',
 'AMY2B',
 'AMY2A',
 'AMY1A',
 'AMY1B',
 'AMY1C',
 'PRMT6',
 'NTNG1',
 'VAV3',
 'SLC25A24',
 'NBPF4',
 'NBPF6',
 'FAM102B',
 'HENMT1',
 'PRPF38B',
 'FNDC7',
 'STXBP3',
 'AKNAD1',
 'GPSM2',
 'CLCC1',
 'WDR47',
 'TAF13',
 'TMEM167B',
 'C1orf194',
 'ELAPOR1',
 'SARS1',
 'CELSR2',
 'PSRC1',
 'MYBPHL',
 'SORT1',
 'PSMA5',
 'SYPL2',
 'ATXN7L2',
 'CYB561D1',
 'AMIGO1',
 'GPR61',
 'GNAI3',
 'GNAT2',
 'AMPD2',
 'GSTM4',
 'GSTM2',
 'GSTM1',
 'GSTM5',
 'GSTM3',
 'EPS8L3',
 'CSF1',
 'AHCYL1',
 'STRIP1',
 'ALX3',
 'UBL4B',
 'SLC6A17',
 'KCNC4',
 'RBM15',
 'SLC16A4',
 'LAMTOR5',
 'PROK1',
 'KCNA10',
 'KCNA2',
 'KCNA3',
 'CD53',
 'LRIF1',
 'DRAM2',
 'CEPT1',
 'DENND2D',
 'CHI3L2',
 'CHIA',
 'PIFO',
 'OVGP1',
 'WDR77',
 'ATP5PB',
 'C1orf162',
 'TMIGD3',
 'ADORA3',
 'RAP1A',
 'INKA2',
 'DDX20',
 'KCND3',
 'CTTNBP2NL',
 'WNT2B',
 'ST7L',
 'CAPZA1',
 'MOV10',
 'RHOC',
 'PPM1J',
 'TAFA3',
 'SLC16A1',
 'LRIG2',
 'MAGI3',
 'PHTF1',
 'RSBN1',
 'PTPN22',
 'BCL2L15',
 'AP4B1',
 'DCLRE1B',
 'HIPK1',
 'OLFML3',
 'SYT6',
 'TRIM33',
 ...]

In [6]:
adata.var['gene_name']=adata.var.index
adata.var['gene_name']

gene_name
Erg28                    Erg28
0610009B22Rik    0610009B22Rik
0610009E02Rik    0610009E02Rik
0610009L18Rik    0610009L18Rik
Dele1                    Dele1
                     ...
mt-Tm                    mt-Tm
mt-Tp                    mt-Tp
mt-Tq                    mt-Tq
mt-Tt                    mt-Tt
mt-Tv                    mt-Tv
Name: gene_name, Length: 16661, dtype: category
Categories (20499, object): ['0610009B22Rik', '0610009E02Rik', '0610009L18Rik', '0610010K14Rik', ..., 'mt-Tq', 'mt-Ts2', 'mt-Tt', 'mt-Tv']

In [7]:
existing_genes = adata.var['gene_name']
existing_genes

gene_name
Erg28                    Erg28
0610009B22Rik    0610009B22Rik
0610009E02Rik    0610009E02Rik
0610009L18Rik    0610009L18Rik
Dele1                    Dele1
                     ...
mt-Tm                    mt-Tm
mt-Tp                    mt-Tp
mt-Tq                    mt-Tq
mt-Tt                    mt-Tt
mt-Tv                    mt-Tv
Name: gene_name, Length: 16661, dtype: category
Categories (20499, object): ['0610009B22Rik', '0610009E02Rik', '0610009L18Rik', '0610010K14Rik', ..., 'mt-Tq', 'mt-Ts2', 'mt-Tt', 'mt-Tv']

In [8]:
# 将所有基因名称转换为小写
all_genes_lower = [gene.lower() for gene in all_genes]
adata_genes_lower = [gene.lower() for gene in existing_genes]

# 将两个列表转换为集合
all_genes_set = set(all_genes_lower)
adata_genes_set = set(adata_genes_lower)

# 计算交集
matching_genes = all_genes_set.intersection(adata_genes_set)
matching_count = len(matching_genes)
# 计算不匹配的基因
non_matching_genes = adata_genes_set - matching_genes
non_matching_count = len(non_matching_genes)


# 输出结果
print(f"匹配的基因数量: {matching_count}")
print(f"匹配的基因列表: {matching_genes}")
non_matching_genes

匹配的基因数量: 13074

{'1110002j07rik',
 'slc22a27',
 '4933439c10rik',
 'otx2os1',
 '4930461g14rik',
 'gm4189',
 'gm32950',
 'zfp503',
 'map2k3os',
 'nupr1l',
 'atxn7l1os1',
 '6030445d17rik',
 'adrm1b',
 '2700049a03rik',
 'gm11536',
 'gm42879',
 'b930094e09rik',
 'vmn2r59',
 'bmyc',
 'gm17244',
 'gm26569',
 'gm29012',
 'gm19583',
 'gm12002',
 'gm21984',
 'a230004m16rik',
 'zfp729b',
 '4933436i20rik',
 'gm16201',
 'gm7334',
 'gm11149',
 '1110025m09rik',
 '1110038f14rik',
 'gm4076',
 'gm16364_ensmusg00000086915',
 'gm37163',
 'gm26740',
 '2410003l11rik',
 'gm28039',
 '9930014a18rik',
 'gm12121',
 'zfp874b',
 '9930111j21rik2',
 'gm26826',
 'gm29666',
 'prox1os',
 'gm28557',
 '4732465j04rik',
 'ccdc142os',
 'etohd2',
 '4930412c18rik',
 'gm43437',
 'gm37571',
 '4930429f24rik',
 'zfp455',
 'a930029g22rik',
 'ifit1bl2',
 'fam149b',
 'gm21973',
 '2310039h08rik',
 'zfp791',
 'gm43844',
 'gm15563',
 'gm10115',
 'akr1cl',
 'gm20939',
 'gm43143',
 'mir100hg',
 'gm14508',
 'gm20492',
 'gm14022',
 'g530011o06rik',
 'etaa1os',
 'gm10555',
 'c530005a16rik',
 'gm29088',
 'd630003m21rik',
 'cyp2d26',
 'gm8013',
 'zfp948',
 'gm17690',
 'bc065397',
 'h1f0',
 'gata6os',
 'gm4221',
 'frg2f1',
 'car3',
 '2310039l15rik',
 'gm17473',
 '1700067k01rik',
 'zfp579',
 'cyp4a12b',
 'lyz2',
 'gm43339',
 '6430571l13rik',
 'gm13412',
 'h1f2',
 '5430402o13rik',
 'gm40348',
 'gm26616',
 'gm38066',
 'cym',
 '9130604c24rik',
 'nopchap1',
 'sars',
 'gm26782',
 'zfp869',
 'zfp329',
 '4931429p17rik',
 'a530041m06rik',
 'gm28959',
 'a230056p14rik',
 'pard3bos3',
 '2010320o07rik',
 'car4',
 'd630023f18rik',
 'gm28403',
 'gm7160',
 'gm17116',
 'trp63',
 'nrg1_ensmusg00000062991',
 '2810407a14rik',
 '9530036o11rik',
 'zfp954',
 'gm43814',
 '4932441j04rik',
 'au015336',
 'gm15883',
 'd830026i12rik',
 'zfp644',
 'gm17484',
 'klk1b22',
 'gm15418',
 '2900076a07rik',
 'gm37186',
 'bfar_ensmusg00000079737',
 'bbln',
 'abcb1a',
 'gm38082',
 'serhl',
 'zfp326',
 'acot10',
 'gm38014',
 'zfp422',
 'gm20707',
 'gm42556',
 '1700010k24rik',
 '1110046j04rik',
 'gm16863',
 '2810405f17rik',
 'gm16536',
 'eprs',
 'h2-t24',
 'akr1b8',
 'd430018e03rik',
 'gm12216',
 'mroh5',
 'zfp607b',
 'ces1d',
 'gm32200',
 'zfp830',
 'zfp52',
 'tmem51os1',
 'aldoart1',
 'zfp873',
 'gm29292',
 'zfp775',
 '9030624g23rik',
 'ccdc7b',
 'gm10804',
 'hmga1b',
 '2700062c07rik',
 'gm16835',
 'taco1os',
 '6720475m21rik',
 'zfp109',
 'ftl1',
 'oas1c',
 'gm13563',
 'gm42432',
 'zfp574',
 '2310061i04rik',
 'gm26691',
 '6330410l21rik',
 'gm16845',
 'gm43331',
 'zfp653',
 'zfp358',
 'gm42929',
 'gm12766',
 'gm42992',
 'gm37893',
 'arxes2',
 'zfp334',
 'gm42991',
 'hotairm1',
 'h2bc27',
 'zfp81',
 'zfp398',
 'akr1c14',
 'gm43254',
 'rnaset2b',
 'dynlt1c',
 '1700055d18rik',
 'gm37082',
 'zfp800',
 'gm36266',
 'mzt2',
 'a430035b10rik',
 'gm37376',
 'gm43788',
 'tex21',
 'gm20655',
 'zfp174',
 'slc35e2',
 '1700021n21rik',
 'zfp113',
 'gm26749',
 '9230112e08rik',
 'ces1h',
 'gm20521',
 'fhip1b',
 '2610507i01rik',
 'trp53i13',
 'a730049h05rik',
 'sspo',
 'gm43813',
 'gm37420',
 'ai661453',
 'zfp105',
 'gm26648',
 'gm26588',
 'appbp2os',
 '4930477o15rik',
 'zfp941',
 '2310040g07rik',
 'gm15581',
 'ifi206',
 'ifit1bl1',
 '2700038g22rik',
 '1110059e24rik',
 'gm9847',
 'zfp747',
 'skint2',
 'skic3',
 'h1f4',
 'h2-dmb2',
 'gm34240',
 'a730011c13rik',
 '4933430i17rik',
 'c130074g19rik',
 'serf1',
 'bc049715',
 'gm45753',
 'csf2rb2',
 'gm16279',
 'gm5532',
 'hbb-bs',
 'gm17354',
 'chn1os3',
 'zfp990',
 '2510016d11rik',
 'gm26885',
 'gm20743',
 '4833420g17rik',
 'akr1c18',
 'gm19272',
 'au019990',
 'gm19684',
 '4930441j16rik',
 'gm14379',
 'zfp956',
 'cyp4a14',
 '9330198n18rik',
 'nherf1',
 'ptp4a1_ensmusg00000026064',
 'rab7',
 'ccdc84',
 'mterf1a',
 '2810001g20rik',
 '2310009b15rik',
 'mfsd13b',
 'cd8b1',
 'gm26660',
 'bc037032',
 'tescl',
 '3110082i17rik',
 'gm26801',
 'b020011l13rik',
 'cfap95',
 'gm42937',
 'gm15398',
 'gm43681',
 'gm4787',
 '1700111n16rik',
 'gm11131',
 'b130046b21rik',
 'gm30097',
 'zfp638',
 'gm9929',
 '2610016a17rik',
 'sanbr',
 '1700101i11rik',
 'gm42826',
 'fam122a',
 'cstpp1',
 'zfp93',
 'gm11476',
 'zfp458',
 'rars',
 'igha',
 'gm36955',
 'gm9903',
 '1700010j16rik',
 '1700030j22rik',
 'them7',
 '2310015k22rik',
 'gm14636',
 'gm43848',
 'keg1',
 'rnps1-ps',
 'gm15983',
 'uqcc4',
 'zfp938',
 'aox2',
 'zfp111',
 'gm37273',
 'gm38375',
 'isoc2a',
 'gm43268',
 'gm3248',
 'zfp790',
 '4930417h01rik',
 'gm37297',
 'gm45713',
 '6030443j06rik',
 '1110065p20rik',
 '8030462n17rik',
 'gm42897',
 'rps23rg1',
 'srsf3-ps',
 'gm42890',
 'cfap68',
 'uchl4',
 'gm29123',
 'gm43466',
 '4933427e11rik',
 'zfp612',
 'c130013h08rik',
 '1700123o20rik',
 'b230317f23rik',
 'gm14019',
 'gm37879',
 'qars',
 '4933431k14rik',
 '9130204k15rik',
 'zfp866',
 'cyp4f17',
 'gm9968',
 'atp5k',
 'gm14412',
 '6030442k20rik',
 'tmem198b',
 'gm15417',
 'gm7030',
 'zfp462',
 'gm15420',
 'tha1',
 'ccdc39',
 'gm10785',
 'zfp438',
 'e030013i19rik',
 'serpina3n',
 'gm15889',
 'cetn4',
 'gm37820',
 '4930511m06rik',
 'igkc',
 'gm16083',
 'gramd3',
 'gm26555',
 'a430057m04rik',
 'gm13684',
 '4921515e04rik',
 'aa986860',
 'gm43259',
 '9530068e07rik',
 'gm10814',
 'gm21781',
 'gm29427',
 'gm43307',
 'f930017d23rik',
 'gm12185',
 'bc035947',
 'd830032e09rik',
 'zmiz1os1',
 'gm43713',
 'atosa',
 'eeig2',
 'h2ac25',
 'gm10638',
 'mir124-2hg',
 'bod1l',
 'zfp868',
 '1700108f19rik',
 'gm38009',
 'gm15564',
 'gm12798',
 'zfp169',
 'gm20449',
 'rbm12b2',
 'adss',
 '1110059g10rik',
 'pals2',
 'gm26666',
 'gm6712',
 'siglecg',
 'gm37052',
 '2610037d02rik',
 'fhip1a',
 'gm14051',
 'zfp804a',
 'gm43646',
 'catspere2',
 'gm43062',
 'xndc1',
 'zfp944',
 '1110004f10rik',
 'pinx1',
 '2810030d12rik',
 'cyp2j5',
 'gm30211',
 'supt5',
 'cep83os',
 'gm31728',
 '2810459m11rik',
 'gm26770',
 'gm15938',
 'b130024g19rik',
 'tomm6os',
 'gm37320',
 '3110045c21rik',
 'gm28035',
 'car10',
 '1110002l01rik',
 'rsph3a',
 'zfp160',
 'rapgef3os2',
 'klk1b5',
 'gm37019',
 'aa386476',
 '2010109a12rik',
 'gm17090',
 'gm42986',
 '0610040f04rik',
 'ces2g',
 '5730480h06rik',
 '1810055g02rik',
 'plxna4os1',
 'bc031181',
 'gm35585',
 'gm44503',
 'has2os',
 '2300002m23rik',
 'h2-ob',
 'gm37204',
 'gm16010',
 'gm15446',
 'ctla2b',
 'oasl2',
 '4930513d17rik',
 'gm11638',
 'gm43328',
 '4930405a21rik',
 'ay702103',
 '1810044d09rik',
 'gm4419',
 'd930020b18rik',
 'gm10036',
 'gm21986',
 'h2-q7',
 'c7_ensmusg00000079105',
 'gm10974',
 '9530046b11rik',
 'gm20186',
 'gm16549',
 'gm10561',
 'zfp518b',
 'zfp558',
 '0610025j13rik',
 'zfp879',
 'c130071c03rik',
 '1700120c14rik',
 '2210408i21rik',
 'gm15651',
 'c230035i16rik',
 '2210406o10rik',
 'ly6f',
 'zfp146',
 '5730409e04rik',
 'nrd1',
 'gm26631',
 'zfp580',
 'gm43672',
 '4930481b07rik',
 'gm44574',
 'a430027c01rik',
 '4931403e22rik',
 'dynlt1f',
 'gm17541',
 'a530017d24rik',
 'gm12843',
 'psme2b',
 'gm38120',
 'gm43573',
 'tmem191',
 'aw112010',
 'zfp87',
 'gm17750',
 'gm42420',
 'zfp185',
 'mir17hg',
 '1700048o20rik',
 '4931422a03rik',
 'cntnap5a',
 'gm12940',
 'gm15551',
 'mt-rnr2',
 'gm29093',
 '4632427e13rik',
 'd130020l05rik',
 'ren1',
 '1700030n03rik',
 'cyp4f14',
 '4930589o11rik',
 '1600025m17rik',
 'gm20268',
 'vars',
 'a330069k06rik',
 'gm26978',
 'hoxd3os1',
 'gm10699',
 'aw822252_ensmusg00000085998',
 'albfm1',
 'gm37733',
 'gm43200',
 'gm42697',
 'zfp692',
 'sectm1b',
 'gm17597',
 'isoc2b',
 'av064505',
 'gm10062',
 'zfp182',
 'oacyl',
 'a530072m11rik',
 'tmem45a2',
 'ugt8a',
 'gm12022',
 'gm12968',
 'zfp667',
 'gm43972',
 'ifitm6',
 '2900092c05rik',
 'gm43387',
 'zfp119a',
 'zfp719',
 'hsd3b9',
 'gm8797',
 'gm16833',
 'zfp277',
 'fabp3-ps1',
 'ly6c1',
 '8430432a02rik',
 'gad1os',
 'ms4a4d',
 'gm27027',
 'zfp977',
 'h3f3aos',
 'gm6665',
 'gm21974',
 'matr3',
 'gm16675',
 'gm10762',
 'rnaset2a',
 'ai115009',
 'gm29514',
 'casc1',
 '9130024f11rik',
 '4930544i03rik',
 '2410006h16rik',
 'arhgap27os2',
 'ube2d2a',
 '2210016l21rik',
 'hprt',
 'spin2c',
 'gm5422',
 '1500026h17rik',
 'gt(rosa)26sor',
 'gm12500',
 'gm14167',
 'zfp346',
 'gvin2',
 'gm15343',
 'gm11716',
 'a930005h10rik',
 'gm15246',
 'lto1_ensmusg00000031072',
 'nherf2',
 'tgtp2',
 'bc029722',
 'atp5b',
 'gm15241',
 'av039307',
 'gm37223',
 'washc2',
 'utp14b',
 'gm20708',
 '4632404h12rik',
 'tmem170',
 'ifi211',
 'prdm16os',
 '9130221h12rik',
 'gm16618',
 '6720489n17rik',
 'gm5460',
 'gm15895',
 'ighg2c',
 'c030007h22rik',
 'fam169b',
 '4833412k13rik',
 'gm20036',
 'skint4',
 'bc043934',
 'zfp72',
 'gm527',
 'gm27224',
 'gm20538',
 'gm42548',
 '4933433g15rik',
 'gm12068',
 'gm30173',
 'ai838599',
 'rsph3b',
 'gm11464',
 '2810429i04rik',
 'bvht',
 'gm19705',
 'gm37336',
 'g730003c15rik',
 'slfn3',
 'abcg3',
 'gm20752',
 'gm12258',
 '2810029c07rik',
 'bc005624',
 'gm37311',
 'sap18b',
 'a230103j11rik',
 'gm26627',
 'cdcp3',
 'serpina1d',
 'ai480526',
 'gm42659',
 'gm37983',
 '1700019a02rik',
 'zfp865',
 'gm19967',
 'gm973',
 'gm807',
 'bc055308',
 'tnfsfm13',
 'gm7694',
 'gm13844',
 '4833413g10rik',
 'gm43081',
 'gm15892',
 'gm37954',
 'ccl6',
 'gm6787',
 'rps18-ps3',
 'ccdc162',
 'gm29282',
 'iars',
 'mtrfr',
 'gm38111',
 'gm10244',
 'doc2g',
 'gm26965',
 '9430034n14rik',
 '4930515g01rik',
 '2810002d19rik',
 'd630029k05rik',
 'eif1a',
 'gm15473',
 'sirpb1b',
 'gm11998',
 'gm11944',
 'ttc7',
 'gm13840',
 'gm43667',
 'akr1e1',
 'gm38021',
 'gm43858',
 '2610203c22rik',
 'h2-m3',
 'snhg15',
 'zfp629',
 'gm26850',
 'ly6i',
 '1700001l05rik',
 'gm26814',
 '9330159m07rik',
 'scd1',
 '2410004b18rik',
 'b230319c09rik',
 '4632428c04rik',
 'eif1ad3',
 'gm20442',
 'gm37403',
 'gm43482',
 'gm27216',
 'zfp963',
 'c430042m11rik',
 'halr1',
 'gm26236',
 '4933429h19rik',
 'gm43274',
 'zfp281',
 'zfp85',
 'zfp750',
 'gm15611',
 'reno1',
 'acnat2',
 'gm11337',
 'gm32554',
 'c730034f03rik',
 'gm42856',
 'car5b',
 'zfp101',
 'zfp773',
 'a330041j22rik',
 'gm26632',
 'car14',
 'e330034l11rik',
 'ifi47',
 'a230001m10rik',
 'gm20404',
 'cyp4a10',
 '9830144p21rik',
 'd430001f17rik',
 'zfp748',
 'bc035044',
 'zfp951',
 '2210408f21rik',
 'gm15962',
 'e330020d12rik',
 '3100003l05rik',
 'zfp273',
 '4930550c14rik',
 'siah1a',
 'cyp2a4',
 'zfp780b',
 'gm10766',
 'cd59a',
 'gm37485',
 'trgc2',
 'unc45bos',
 'a730017l22rik',
 'slc6a20b',
 'zfp622',
 'b230217o12rik',
 'gm38357',
 'ints15',
 '4930509g22rik',
 'zfp275',
 'gm4673',
 'd930048n14rik',
 'gpi-ps',
 'epb41l4aos',
 'a230065n10rik',
 'a430110l20rik',
 'gm37383',
 'gm38329',
 'sult1d1',
 '6030400a10rik',
 'jpx',
 'eif1ad8',
 'gm6225',
 '1700064h15rik',
 'tnfrsf26',
 'gm55594',
 'zfp961',
 'd030055h07rik',
 'gm29242',
 'platr21',
 'oasl1',
 'gm12963',
 'gm28375',
 'gm29283',
 '1810062g17rik',
 'zpld2',
 'gm11751',
 'gm5424',
 'hnf4aos',
 'gm13855',
 'bb014433',
 'gm43300',
 'skint5',
 'gm13421',
 'gm15510',
 'gm12472',
 'gm15634',
 'gm15958',
 'gm43605',
 'gm12184',
 'a930012l18rik',
 'b230216n24rik',
 'gm43029',
 'csnk2a1-ps3',
 'rnu4atac',
 '3110099e03rik',
 'gm10461',
 'ces2e',
 'a430110c17rik',
 'gm37531',
 'zfp946',
 'b630019k06rik',
 'cd1d2',
 '3830406c13rik',
 'gm15218',
 '6430511e19rik',
 'gm43312',
 'gm20476',
 'gm12676',
 '2410022m11rik',
 'zfp512b',
 'gm28052',
 'ai854703',
 'kap',
 'trim12c',
 '4930573h18rik',
 'supt20',
 'gm16973',
 '9030407p20rik',
 'gm26947',
 '3110056k07rik',
 'c330013e15rik',
 'gm37584',
 '2200002d01rik',
 'a730036i17rik',
 'gpi1',
 'eci3',
 'gm43201',
 'irgm1',
 'd930036k23rik',
 'gm12596',
 'lipo2',
 'gm5141',
 'zfp316',
 'gm28982',
 'abca16',
 'gm15787',
 'h2-ab1',
 'tubb5',
 'gm15408',
 'zfp955b',
 '3110040n11rik',
 'tarsl2',
 'h2-t22',
 'gm17146',
 'gm43343',
 'uqcc5',
 'gm42549',
 'gm42979',
 'gm28826',
 'emx2os',
 'gm17178',
 'tprgl',
 'naip5',
 'gm20755',
 '1700081b01rik',
 'gm28404',
 '2310030g06rik',
 'snhg8',
 '1700057g04rik',
 'zfp65',
 'cyp4f18',
 'gm7467',
 'trp53inp1',
 'vmn2r68',
 'car9',
 'gm26862',
 'plekhd1os',
 'gm17530',
 'gm43055',
 'bc024978',
 'gm43566',
 'gm9920',
 'gm43593',
 'e030030i06rik',
 'rnf113a1',
 'airn',
 'gm28037',
 'gm15848',
 'zfp617',
 'd430013b06rik',
 'clca3a1',
 'gm37914',
 'gm42772',
 'snhg12',
 '4930586n03rik',
 '5930420m18rik',
 'gm43821',
 'a830082k12rik',
 'gm10605',
 'xntrpc',
 '9630028h03rik',
 'zfp945',
 'gm15903',
 '2700097o09rik',
 'gm17066',
 'abca17',
 'gm10687',
 '1700095j07rik',
 'gm37902',
 'gm19426',
 'ccl9',
 'gm9755',
 'runx2os1',
 'gm9754',
 'nt5c3',
 'gm42895',
 'zfp94',
 'gm3604',
 'ifi202b',
 'mettl5os',
 'gm23458',
 '4930557j02rik',
 '5031434o11rik',
 'gm38392',
 'aw209491',
 'gm42981',
 '9930104l06rik',
 'gm37860',
 'a530020g20rik',
 '1110019d14rik',
 'zfp426',
 'mir22hg',
 'gm37466',
 'gm16124',
 'pirb',
 'gm13267',
 '4921539e11rik',
 'gm16793',
 'e230029c05rik',
 'zfp984',
 'c330002g04rik',
 '1500004a13rik',
 '4933425m03rik',
 'gm10516',
 '2610020c07rik',
 'b230208h11rik',
 'gm5134',
 '6430548m08rik',
 'gm38211',
 'zfp871',
 'fbxl9',
 'gm43481',
 'snhg11',
 'lhfp',
 'klk1b3',
 '4930473a02rik',
 'septin2_ensmusg00000026276',
 'slc22a21',
 'dnaaf9',
 'sypl',
 'gm42568',
 '1810041h14rik',
 'a130051j06rik',
 'gcat_ensmusg00000006378',
 'trp53inp2',
 'gm38393',
 'gm43860',
 'aa474408',
 'zfp382',
 'a730081d07rik',
 'a330008l17rik',
 'akr1c20',
 'nars',
 'nat8f1',
 'gm49405',
 'ai504432',
 '1700017b05rik',
 '1700034h15rik',
 'zfp768',
 '4930579k19rik',
 'gm16310',
 'cd300c2',
 'gm28874',
 ...}

In [9]:
gene_to_index = {gene: idx for idx, gene in enumerate(all_genes_lower)}
gene_to_index

{'or4f5': 0,
 'or4f29': 1,
 'or4f16': 2,
 'samd11': 3,
 'noc2l': 4,
 'klhl17': 5,
 'plekhn1': 6,
 'perm1': 7,
 'hes4': 8,
 'isg15': 9,
 'agrn': 10,
 'rnf223': 11,
 'c1orf159': 12,
 'ttll10': 13,
 'tnfrsf18': 14,
 'tnfrsf4': 15,
 'sdf4': 16,
 'b3galt6': 17,
 'c1qtnf12': 18,
 'ube2j2': 19,
 'scnn1d': 20,
 'acap3': 21,
 'pusl1': 22,
 'ints11': 23,
 'cptp': 24,
 'tas1r3': 25,
 'dvl1': 26,
 'mxra8': 27,
 'aurkaip1': 28,
 'ccnl2': 29,
 'mrpl20': 30,
 'ankrd65': 31,
 'tmem88b': 32,
 'vwa1': 33,
 'atad3c': 34,
 'atad3b': 35,
 'atad3a': 36,
 'tmem240': 37,
 'ssu72': 38,
 'fndc10': 39,
 'mib2': 40,
 'mmp23b': 41,
 'cdk11b': 42,
 'slc35e2b': 43,
 'cdk11a': 44,
 'nadk': 45,
 'gnb1': 46,
 'calml6': 47,
 'tmem52': 48,
 'cfap74': 49,
 'gabrd': 50,
 'prkcz': 51,
 'faap20': 52,
 'ski': 53,
 'morn1': 54,
 'rer1': 55,
 'pex10': 56,
 'plch2': 57,
 'pank4': 58,
 'hes5': 59,
 'tnfrsf14': 60,
 'prxl2b': 61,
 'mmel1': 62,
 'ttc34': 63,
 'actrt2': 64,
 'prdm16': 65,
 'arhgef16': 66,
 'megf6': 67,
 'tprg1l': 68,
 'wrap73': 69,
 'tp73': 70,
 'ccdc27': 71,
 'smim1': 72,
 'lrrc47': 73,
 'cep104': 74,
 'dffb': 75,
 'c1orf174': 76,
 'ajap1': 77,
 'nphp4': 78,
 'kcnab2': 79,
 'chd5': 80,
 'rpl22': 81,
 'rnf207': 82,
 'icmt': 83,
 'hes3': 84,
 'gpr153': 85,
 'acot7': 86,
 'hes2': 87,
 'espn': 88,
 'tnfrsf25': 89,
 'plekhg5': 90,
 'nol9': 91,
 'tas1r1': 92,
 'zbtb48': 93,
 'klhl21': 94,
 'phf13': 95,
 'thap3': 96,
 'dnajc11': 97,
 'camta1': 98,
 'vamp3': 99,
 'per3': 100,
 'uts2': 101,
 'tnfrsf9': 102,
 'park7': 103,
 'errfi1': 104,
 'slc45a1': 105,
 'rere': 106,
 'eno1': 107,
 'ca6': 108,
 'slc2a7': 109,
 'slc2a5': 110,
 'gpr157': 111,
 'h6pd': 112,
 'spsb1': 113,
 'slc25a33': 114,
 'tmem201': 115,
 'pik3cd': 116,
 'clstn1': 117,
 'ctnnbip1': 118,
 'lzic': 119,
 'nmnat1': 120,
 'rbp7': 121,
 'ube4b': 122,
 'kif1b': 123,
 'pgd': 124,
 'cenps': 125,
 'cort': 126,
 'dffa': 127,
 'pex14': 128,
 'casz1': 129,
 'c1orf127': 130,
 'tardbp': 131,
 'masp2': 132,
 'srm': 133,
 'exosc10': 134,
 'mtor': 135,
 'angptl7': 136,
 'ubiad1': 137,
 'disp3': 138,
 'fbxo2': 139,
 'fbxo44': 140,
 'fbxo6': 141,
 'mad2l2': 142,
 'draxin': 143,
 'agtrap': 144,
 'c1orf167': 145,
 'mthfr': 146,
 'clcn6': 147,
 'nppa': 148,
 'nppb': 149,
 'kiaa2013': 150,
 'plod1': 151,
 'mfn2': 152,
 'miip': 153,
 'tnfrsf8': 154,
 'tnfrsf1b': 155,
 'vps13d': 156,
 'dhrs3': 157,
 'aadacl4': 158,
 'aadacl3': 159,
 'c1orf158': 160,
 'pramef12': 161,
 'pramef1': 162,
 'pramef11': 163,
 'hnrnpcl1': 164,
 'pramef2': 165,
 'pramef4': 166,
 'pramef10': 167,
 'pramef7': 168,
 'pramef6': 169,
 'pramef27': 170,
 'hnrnpcl3': 171,
 'pramef25': 172,
 'hnrnpcl2': 173,
 'pramef26': 174,
 'hnrnpcl4': 175,
 'pramef9': 176,
 'pramef13': 177,
 'pramef18': 178,
 'pramef5': 179,
 'pramef8': 180,
 'pramef33': 181,
 'pramef15': 182,
 'pramef14': 183,
 'pramef19': 184,
 'pramef17': 185,
 'pramef20': 186,
 'lrrc38': 187,
 'pdpn': 188,
 'prdm2': 189,
 'kazn': 190,
 'tmem51': 191,
 'fhad1': 192,
 'efhd2': 193,
 'ctrc': 194,
 'cela2a': 195,
 'cela2b': 196,
 'casp9': 197,
 'dnajc16': 198,
 'agmat': 199,
 'ddi2': 200,
 'rsc1a1': 201,
 'plekhm2': 202,
 'slc25a34': 203,
 'tmem82': 204,
 'fblim1': 205,
 'uqcrhl': 206,
 'spen': 207,
 'zbtb17': 208,
 'srarp': 209,
 'hspb7': 210,
 'clcnka': 211,
 'clcnkb': 212,
 'fam131c': 213,
 'epha2': 214,
 'arhgef19': 215,
 'cplane2': 216,
 'fbxo42': 217,
 'szrd1': 218,
 'spata21': 219,
 'necap2': 220,
 'nbpf1': 221,
 'crocc': 222,
 'mfap2': 223,
 'atp13a2': 224,
 'sdhb': 225,
 'padi2': 226,
 'padi1': 227,
 'padi3': 228,
 'padi4': 229,
 'padi6': 230,
 'rcc2': 231,
 'arhgef10l': 232,
 'actl8': 233,
 'igsf21': 234,
 'klhdc7a': 235,
 'pax7': 236,
 'tas1r2': 237,
 'aldh4a1': 238,
 'iffo2': 239,
 'ubr4': 240,
 'emc1': 241,
 'mrto4': 242,
 'akr7a3': 243,
 'akr7a2': 244,
 'slc66a1': 245,
 'capzb': 246,
 'micos10': 247,
 'nbl1': 248,
 'htr6': 249,
 'tmco4': 250,
 'rnf186': 251,
 'otud3': 252,
 'pla2g2e': 253,
 'pla2g2a': 254,
 'pla2g5': 255,
 'pla2g2d': 256,
 'pla2g2f': 257,
 'pla2g2c': 258,
 'ubxn10': 259,
 'vwa5b1': 260,
 'camk2n1': 261,
 'mul1': 262,
 'fam43b': 263,
 'cda': 264,
 'pink1': 265,
 'ddost': 266,
 'kif17': 267,
 'sh2d5': 268,
 'hp1bp3': 269,
 'eif4g3': 270,
 'ece1': 271,
 'nbpf3': 272,
 'alpl': 273,
 'rap1gap': 274,
 'usp48': 275,
 'ldlrad2': 276,
 'hspg2': 277,
 'cela3b': 278,
 'cela3a': 279,
 'cdc42': 280,
 'wnt4': 281,
 'zbtb40': 282,
 'epha8': 283,
 'c1qa': 284,
 'c1qc': 285,
 'c1qb': 286,
 'ephb2': 287,
 'lactbl1': 288,
 'tex46': 289,
 'kdm1a': 290,
 'luzp1': 291,
 'htr1d': 292,
 'hnrnpr': 293,
 'znf436': 294,
 'tcea3': 295,
 'asap3': 296,
 'e2f2': 297,
 'id3': 298,
 'rpl11': 299,
 'eloa': 300,
 'pithd1': 301,
 'lypla2': 302,
 'gale': 303,
 'hmgcl': 304,
 'fuca1': 305,
 'cnr2': 306,
 'pnrc2': 307,
 'srsf10': 308,
 'myom3': 309,
 'il22ra1': 310,
 'ifnlr1': 311,
 'grhl3': 312,
 'stpg1': 313,
 'nipal3': 314,
 'rcan3': 315,
 'ncmap': 316,
 'srrm1': 317,
 'clic4': 318,
 'runx3': 319,
 'syf2': 320,
 'rsrp1': 321,
 'rhd': 322,
 'tmem50a': 323,
 'rhce': 324,
 'maco1': 325,
 'ldlrap1': 326,
 'man1c1': 327,
 'selenon': 328,
 'mtfr1l': 329,
 'aunip': 330,
 'paqr7': 331,
 'stmn1': 332,
 'pafah2': 333,
 'extl1': 334,
 'slc30a2': 335,
 'trim63': 336,
 'pdik1l': 337,
 'fam110d': 338,
 'c1orf232': 339,
 'znf593os': 340,
 'znf593': 341,
 'cnksr1': 342,
 'catsper4': 343,
 'cep85': 344,
 'sh3bgrl3': 345,
 'ubxn11': 346,
 'cd52': 347,
 'crybg2': 348,
 'znf683': 349,
 'lin28a': 350,
 'dhdds': 351,
 'hmgn2': 352,
 'rps6ka1': 353,
 'arid1a': 354,
 'pigv': 355,
 'zdhhc18': 356,
 'sfn': 357,
 'gpn2': 358,
 'gpatch3': 359,
 'nudc': 360,
 'nr0b2': 361,
 'kdf1': 362,
 'trnp1': 363,
 'tent5b': 364,
 'slc9a1': 365,
 'wdtc1': 366,
 'tmem222': 367,
 'sytl1': 368,
 'map3k6': 369,
 'fcn3': 370,
 'cd164l2': 371,
 'gpr3': 372,
 'wasf2': 373,
 'ahdc1': 374,
 'fgr': 375,
 'ifi6': 376,
 'fam76a': 377,
 'stx12': 378,
 'ppp1r8': 379,
 'themis2': 380,
 'rpa2': 381,
 'smpdl3b': 382,
 'xkr8': 383,
 'eya3': 384,
 'ptafr': 385,
 'dnajc8': 386,
 'atp5if1': 387,
 'sesn2': 388,
 'med18': 389,
 'phactr4': 390,
 'rcc1': 391,
 'trnau1ap': 392,
 'taf12': 393,
 'rab42': 394,
 'gmeb1': 395,
 'ythdf2': 396,
 'oprd1': 397,
 'epb41': 398,
 'tmem200b': 399,
 'srsf4': 400,
 'mecr': 401,
 'ptpru': 402,
 'matn1': 403,
 'laptm5': 404,
 'sdc3': 405,
 'pum1': 406,
 'nkain1': 407,
 'snrnp40': 408,
 'zcchc17': 409,
 'fabp3': 410,
 'serinc2': 411,
 'tinagl1': 412,
 'hcrtr1': 413,
 'pef1': 414,
 'col16a1': 415,
 'adgrb2': 416,
 'spocd1': 417,
 'ptp4a2': 418,
 'khdrbs1': 419,
 'tmem39b': 420,
 'kpna6': 421,
 'txlna': 422,
 'ccdc28b': 423,
 'iqcc': 424,
 'dcdc2b': 425,
 'tmem234': 426,
 'eif3i': 427,
 'fam167b': 428,
 'lck': 429,
 'hdac1': 430,
 'marcksl1': 431,
 'tssk3': 432,
 'fam229a': 433,
 'bsdc1': 434,
 'zbtb8b': 435,
 'zbtb8a': 436,
 'zbtb8os': 437,
 'rbbp4': 438,
 'sync': 439,
 'kiaa1522': 440,
 'yars1': 441,
 's100pbp': 442,
 'fndc5': 443,
 'hpca': 444,
 'tmem54': 445,
 'rnf19b': 446,
 'ak2': 447,
 'azin2': 448,
 'trim62': 449,
 'znf362': 450,
 'a3galt2': 451,
 'phc2': 452,
 'zscan20': 453,
 'csmd2': 454,
 'hmgb4': 455,
 'c1orf94': 456,
 'smim12': 457,
 'gjb5': 458,
 'gjb4': 459,
 'gjb3': 460,
 'gja4': 461,
 'dlgap3': 462,
 'tmem35b': 463,
 'zmym6': 464,
 'zmym1': 465,
 'sfpq': 466,
 'zmym4': 467,
 'kiaa0319l': 468,
 'ncdn': 469,
 'tfap2e': 470,
 'psmb2': 471,
 'c1orf216': 472,
 'clspn': 473,
 'ago4': 474,
 'ago1': 475,
 'ago3': 476,
 'tekt2': 477,
 'adprs': 478,
 'col8a2': 479,
 'trappc3': 480,
 'map7d1': 481,
 'thrap3': 482,
 'sh3d21': 483,
 'eva1b': 484,
 'stk40': 485,
 'lsm10': 486,
 'oscp1': 487,
 'mrps15': 488,
 'csf3r': 489,
 'grik3': 490,
 'zc3h12a': 491,
 'meaf6': 492,
 'snip1': 493,
 'dnali1': 494,
 'gnl2': 495,
 'rspo1': 496,
 'c1orf109': 497,
 'cdca8': 498,
 'epha10': 499,
 'maneal': 500,
 'yrdc': 501,
 'c1orf122': 502,
 'mtf1': 503,
 'inpp5b': 504,
 'sf3a3': 505,
 'fhl3': 506,
 'utp11': 507,
 'pou3f1': 508,
 'rragc': 509,
 'mycbp': 510,
 'gja9': 511,
 'rhbdl2': 512,
 'akirin1': 513,
 'ndufs5': 514,
 'macf1': 515,
 'bmp8a': 516,
 'pabpc4': 517,
 'heyl': 518,
 'nt5c1a': 519,
 'hpcal4': 520,
 'ppie': 521,
 'bmp8b': 522,
 'oxct2': 523,
 'trit1': 524,
 'mycl': 525,
 'mfsd2a': 526,
 'cap1': 527,
 'ppt1': 528,
 'rlf': 529,
 'tmco2': 530,
 'zmpste24': 531,
 'col9a2': 532,
 'smap2': 533,
 'zfp69b': 534,
 'zfp69': 535,
 'exo5': 536,
 'znf684': 537,
 'rims3': 538,
 'nfyc': 539,
 'kcnq4': 540,
 'cited4': 541,
 'ctps1': 542,
 'slfnl1': 543,
 'scmh1': 544,
 'foxo6': 545,
 'edn2': 546,
 'hivep3': 547,
 'guca2b': 548,
 'guca2a': 549,
 'foxj3': 550,
 'rimkla': 551,
 'zmynd12': 552,
 'ppcs': 553,
 'ccdc30': 554,
 'ppih': 555,
 'ybx1': 556,
 'cldn19': 557,
 'p3h1': 558,
 'c1orf50': 559,
 'tmem269': 560,
 'svbp': 561,
 'ermap': 562,
 'znf691': 563,
 'slc2a1': 564,
 'fam183a': 565,
 'ebna1bp2': 566,
 'cfap57': 567,
 'tmem125': 568,
 'c1orf210': 569,
 'tie1': 570,
 'mpl': 571,
 'cdc20': 572,
 'elovl1': 573,
 'med8': 574,
 'szt2': 575,
 'hyi': 576,
 'ptprf': 577,
 'kdm4a': 578,
 'st3gal3': 579,
 'artn': 580,
 'ipo13': 581,
 'dph2': 582,
 'atp6v0b': 583,
 'b4galt2': 584,
 'ccdc24': 585,
 'slc6a9': 586,
 'klf17': 587,
 'klf18': 588,
 'dmap1': 589,
 'eri3': 590,
 'rnf220': 591,
 'tmem53': 592,
 'armh1': 593,
 'kif2c': 594,
 'rps8': 595,
 'best4': 596,
 'plk3': 597,
 'dynlt4': 598,
 'btbd19': 599,
 'ptch2': 600,
 'eif2b3': 601,
 'hectd3': 602,
 'urod': 603,
 'zswim5': 604,
 'hpdl': 605,
 'mutyh': 606,
 'toe1': 607,
 'tesk2': 608,
 'ccdc163': 609,
 'mmachc': 610,
 'prdx1': 611,
 'akr1a1': 612,
 'nasp': 613,
 'ccdc17': 614,
 'gpbp1l1': 615,
 'tmem69': 616,
 'ipp': 617,
 'mast2': 618,
 'pik3r3': 619,
 'tspan1': 620,
 'p3r3urf': 621,
 'pomgnt1': 622,
 'lurap1': 623,
 'rad54l': 624,
 'lrrc41': 625,
 'uqcrh': 626,
 'nsun4': 627,
 'faah': 628,
 'dmbx1': 629,
 'tmem275': 630,
 'kncn': 631,
 'mknk1': 632,
 'mob3c': 633,
 'atpaf1': 634,
 'tex38': 635,
 'efcab14': 636,
 'cyp4b1': 637,
 'cyp4a11': 638,
 'cyp4x1': 639,
 'cyp4z1': 640,
 'cyp4a22': 641,
 'pdzk1ip1': 642,
 'tal1': 643,
 'stil': 644,
 'cmpk1': 645,
 'foxe3': 646,
 'foxd2': 647,
 'trabd2b': 648,
 'slc5a9': 649,
 'spata6': 650,
 'agbl4': 651,
 'bend5': 652,
 'elavl4': 653,
 'dmrta2': 654,
 'faf1': 655,
 'cdkn2c': 656,
 'c1orf185': 657,
 'rnf11': 658,
 'ttc39a': 659,
 'eps15': 660,
 'osbpl9': 661,
 'nrdc': 662,
 'rab3b': 663,
 'txndc12': 664,
 'kti12': 665,
 'btf3l4': 666,
 'zfyve9': 667,
 'cc2d1b': 668,
 'orc1': 669,
 'prpf38a': 670,
 'tut4': 671,
 'gpx7': 672,
 'shisal2a': 673,
 'coa7': 674,
 'zyg11b': 675,
 'zyg11a': 676,
 'echdc2': 677,
 'scp2': 678,
 'podn': 679,
 'slc1a7': 680,
 'cpt2': 681,
 'czib': 682,
 'magoh': 683,
 'lrp8': 684,
 'dmrtb1': 685,
 'glis1': 686,
 'ndc1': 687,
 'yipf1': 688,
 'dio1': 689,
 'hspb11': 690,
 'lrrc42': 691,
 'ldlrad1': 692,
 'tmem59': 693,
 'tceanc2': 694,
 'cdcp2': 695,
 'cyb5rl': 696,
 'mrpl37': 697,
 'ssbp3': 698,
 'acot11': 699,
 'fam151a': 700,
 'mroh7': 701,
 'ttc4': 702,
 'pars2': 703,
 'ttc22': 704,
 'lexm': 705,
 'dhcr24': 706,
 'tmem61': 707,
 'bsnd': 708,
 'pcsk9': 709,
 'usp24': 710,
 'plpp3': 711,
 'prkaa2': 712,
 'fyb2': 713,
 'c8a': 714,
 'c8b': 715,
 'dab1': 716,
 'oma1': 717,
 'tacstd2': 718,
 'mysm1': 719,
 'jun': 720,
 'fggy': 721,
 'hook1': 722,
 'cyp2j2': 723,
 'c1orf87': 724,
 'nfia': 725,
 'tm2d1': 726,
 'patj': 727,
 'l1td1': 728,
 'kank4': 729,
 'usp1': 730,
 'dock7': 731,
 'angptl3': 732,
 'atg4c': 733,
 'foxd3': 734,
 'alg6': 735,
 'itgb3bp': 736,
 'efcab7': 737,
 'pgm1': 738,
 'ror1': 739,
 'ube2u': 740,
 'cachd1': 741,
 'raver2': 742,
 'jak1': 743,
 'ak4': 744,
 'dnajc6': 745,
 'leprot': 746,
 'lepr': 747,
 'pde4b': 748,
 'sgip1': 749,
 'dynlt5': 750,
 'insl5': 751,
 'dnai4': 752,
 'mier1': 753,
 'slc35d1': 754,
 'c1orf141': 755,
 'il23r': 756,
 'il12rb2': 757,
 'serbp1': 758,
 'gadd45a': 759,
 'gng12': 760,
 'diras3': 761,
 'wls': 762,
 'rpe65': 763,
 'depdc1': 764,
 'lrrc7': 765,
 'lrrc40': 766,
 'srsf11': 767,
 'ankrd13c': 768,
 'cth': 769,
 'ptger3': 770,
 'zranb2': 771,
 'negr1': 772,
 'lrriq3': 773,
 'fpgt': 774,
 'tnni3k': 775,
 'lrrc53': 776,
 'erich3': 777,
 'cryz': 778,
 'tyw3': 779,
 'lhx8': 780,
 'slc44a5': 781,
 'acadm': 782,
 'rabggtb': 783,
 'msh4': 784,
 'asb17': 785,
 'st6galnac3': 786,
 'st6galnac5': 787,
 'pigk': 788,
 'ak5': 789,
 'zzz3': 790,
 'usp33': 791,
 'miga1': 792,
 'nexn': 793,
 'fubp1': 794,
 'dnajb4': 795,
 'gipc2': 796,
 'ptgfr': 797,
 'ifi44l': 798,
 'ifi44': 799,
 'adgrl4': 800,
 'adgrl2': 801,
 'ttll7': 802,
 'prkacb': 803,
 'samd13': 804,
 'dnase2b': 805,
 'rpf1': 806,
 'gng5': 807,
 'spata1': 808,
 'ctbs': 809,
 'ssx2ip': 810,
 'lpar3': 811,
 'mcoln2': 812,
 'dnai3': 813,
 'mcoln3': 814,
 'syde2': 815,
 'c1orf52': 816,
 'bcl10': 817,
 'ddah1': 818,
 'ccn1': 819,
 'znhit6': 820,
 'col24a1': 821,
 'odf2l': 822,
 'clca2': 823,
 'clca1': 824,
 'clca4': 825,
 'sh3glb1': 826,
 'selenof': 827,
 'hs2st1': 828,
 'lmo4': 829,
 'pkn2': 830,
 'gtf2b': 831,
 'kyat3': 832,
 'rbmxl1': 833,
 'gbp3': 834,
 'gbp1': 835,
 'gbp2': 836,
 'gbp7': 837,
 'gbp4': 838,
 'gbp5': 839,
 'gbp6': 840,
 'lrrc8b': 841,
 'lrrc8c': 842,
 'lrrc8d': 843,
 'znf326': 844,
 'barhl2': 845,
 'znf644': 846,
 'hfm1': 847,
 'cdc7': 848,
 'tgfbr3': 849,
 'brdt': 850,
 'ephx4': 851,
 'setsip': 852,
 'btbd8': 853,
 'c1orf146': 854,
 'glmn': 855,
 'rpap2': 856,
 'gfi1': 857,
 'evi5': 858,
 'rpl5': 859,
 'dipk1a': 860,
 'mtf2': 861,
 'tmed5': 862,
 'ccdc18': 863,
 'dr1': 864,
 'fnbp1l': 865,
 'bcar3': 866,
 'dnttip2': 867,
 'gclm': 868,
 'abca4': 869,
 'arhgap29': 870,
 'abcd3': 871,
 'f3': 872,
 'slc44a3': 873,
 'cnn3': 874,
 'alg14': 875,
 'tlcd4': 876,
 'rwdd3': 877,
 'ptbp2': 878,
 'dpyd': 879,
 'snx7': 880,
 'plppr5': 881,
 'plppr4': 882,
 'palmd': 883,
 'frrs1': 884,
 'agl': 885,
 'slc35a3': 886,
 'mfsd14a': 887,
 'sass6': 888,
 'trmt13': 889,
 'lrrc39': 890,
 'dbt': 891,
 'rtca': 892,
 'cdc14a': 893,
 'gpr88': 894,
 'vcam1': 895,
 'extl2': 896,
 'slc30a7': 897,
 'dph5': 898,
 's1pr1': 899,
 'olfm3': 900,
 'col11a1': 901,
 'rnpc3': 902,
 'amy2b': 903,
 'amy2a': 904,
 'amy1a': 905,
 'amy1b': 906,
 'amy1c': 907,
 'prmt6': 908,
 'ntng1': 909,
 'vav3': 910,
 'slc25a24': 911,
 'nbpf4': 912,
 'nbpf6': 913,
 'fam102b': 914,
 'henmt1': 915,
 'prpf38b': 916,
 'fndc7': 917,
 'stxbp3': 918,
 'aknad1': 919,
 'gpsm2': 920,
 'clcc1': 921,
 'wdr47': 922,
 'taf13': 923,
 'tmem167b': 924,
 'c1orf194': 925,
 'elapor1': 926,
 'sars1': 927,
 'celsr2': 928,
 'psrc1': 929,
 'mybphl': 930,
 'sort1': 931,
 'psma5': 932,
 'sypl2': 933,
 'atxn7l2': 934,
 'cyb561d1': 935,
 'amigo1': 936,
 'gpr61': 937,
 'gnai3': 938,
 'gnat2': 939,
 'ampd2': 940,
 'gstm4': 941,
 'gstm2': 942,
 'gstm1': 943,
 'gstm5': 944,
 'gstm3': 945,
 'eps8l3': 946,
 'csf1': 947,
 'ahcyl1': 948,
 'strip1': 949,
 'alx3': 950,
 'ubl4b': 951,
 'slc6a17': 952,
 'kcnc4': 953,
 'rbm15': 954,
 'slc16a4': 955,
 'lamtor5': 956,
 'prok1': 957,
 'kcna10': 958,
 'kcna2': 959,
 'kcna3': 960,
 'cd53': 961,
 'lrif1': 962,
 'dram2': 963,
 'cept1': 964,
 'dennd2d': 965,
 'chi3l2': 966,
 'chia': 967,
 'pifo': 968,
 'ovgp1': 969,
 'wdr77': 970,
 'atp5pb': 971,
 'c1orf162': 972,
 'tmigd3': 973,
 'adora3': 974,
 'rap1a': 975,
 'inka2': 976,
 'ddx20': 977,
 'kcnd3': 978,
 'cttnbp2nl': 979,
 'wnt2b': 980,
 'st7l': 981,
 'capza1': 982,
 'mov10': 983,
 'rhoc': 984,
 'ppm1j': 985,
 'tafa3': 986,
 'slc16a1': 987,
 'lrig2': 988,
 'magi3': 989,
 'phtf1': 990,
 'rsbn1': 991,
 'ptpn22': 992,
 'bcl2l15': 993,
 'ap4b1': 994,
 'dclre1b': 995,
 'hipk1': 996,
 'olfml3': 997,
 'syt6': 998,
 'trim33': 999,
 ...}

In [10]:
only_in_all_genes = all_genes_set - adata_genes_set

only_in_adata_genes = adata_genes_set - all_genes_set

# 输出结果
print(f"仅在 all_genes 中存在的基因数量: {len(only_in_all_genes)}")
print(f"仅在 all_genes 中存在的基因: {only_in_all_genes}")

print(f"仅在 adata_genes 中存在的基因数量: {len(only_in_adata_genes)}")
print(f"仅在 adata_genes 中存在的基因: {only_in_adata_genes}")

仅在 all_genes 中存在的基因数量: 6257

In [11]:
import numpy as np
from scipy.sparse import csr_matrix

# Initialize a mapping from gene names in adata to their column indices
adata_gene_to_index = {gene: idx for idx, gene in enumerate(adata_genes_lower)}

# Create an array to map adata.X column indices to new_data column indices
adata_to_new_data_indices = -1 * np.ones(adata.X.shape[1], dtype=int)
for idx, gene in enumerate(adata_genes_lower):
    if gene in gene_to_index:
        adata_to_new_data_indices[idx] = gene_to_index[gene]



# Extract data from adata.X without converting it to a dense array
data = adata.X.data
indices = adata.X.indices
indptr = adata.X.indptr

# Map the column indices to the new indices in new_data
mapped_indices = adata_to_new_data_indices[indices]

# Filter out entries where the mapping is invalid (-1)
valid_entries = mapped_indices != -1
new_data_values = data[valid_entries]
new_data_indices = mapped_indices[valid_entries]

# Build the new indptr array for the new_data matrix
new_indptr = np.zeros(adata.X.shape[0] + 1, dtype=int)


for i in range(adata.X.shape[0]):
    row_start = indptr[i]
    row_end = indptr[i + 1]
    valid_count = np.sum(valid_entries[row_start:row_end])
    new_indptr[i + 1] = new_indptr[i] + valid_count


# Construct the new_data sparse matrix
new_data = csr_matrix(
    (new_data_values, new_data_indices, new_indptr),
    shape=(adata.X.shape[0], len(all_genes)),
    dtype=np.float32
)
new_data = new_data.toarray()

In [12]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.model_selection import train_test_split


label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(adata.obs['cell_type'])  # 预先编码标签


random_seed = 42
X_train_val, X_test, y_train_val, y_test = train_test_split(
    new_data, labels_encoded, test_size=0.15, random_state=random_seed)


X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.1765, random_state=random_seed)  # 0.1765 是为了让验证集占 15%

from sklearn.decomposition import PCA
n_components = 64
pca = PCA(n_components=n_components)
train_embeddings = pca.fit_transform(X_train)
test_embeddings = pca.transform(X_test)

In [13]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

    

    # 初始化和训练KNN分类器
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_embeddings, y_train)
    
    # 模型预测
predictions = knn.predict(test_embeddings)

    # 计算准确率和 F1 分数
accuracy = accuracy_score(y_test, predictions)
print(f"KNN Accuracy on Test Data: {accuracy}")
f1 = f1_score(y_test, predictions, average='weighted')
print(f"Weighted F1 Score: {f1}")
    
macro_f1 = f1_score(y_test, predictions, average='macro')
print(f'Macro F1 Score: {macro_f1}')

    # 计算随机猜测的准确率
class_probabilities = np.bincount(y_test) / len(y_test)
random_accuracy = np.sum(class_probabilities ** 2)
print(f"Random Guess Accuracy: {random_accuracy}")

    # 生成分类报告
report = classification_report(y_test, predictions, target_names=label_encoder.classes_)
print(report)

KNN Accuracy on Test Data: 0.45692672916750493
Weighted F1 Score: 0.43300296671282257
Macro F1 Score: 0.15475021053735877
Random Guess Accuracy: 0.2526864384339867
                                                           precision    recall  f1-score   support

                          blood vessel smooth muscle cell       0.06      0.06      0.06       483
                                         endothelial cell       0.38      0.56      0.46      7705
                 kidney collecting duct intercalated cell       0.00      0.00      0.00        68
                    kidney collecting duct principal cell       0.05      0.02      0.02       376
          kidney distal convoluted tubule epithelial cell       0.29      0.15      0.19       509
                                     kidney granular cell       0.00      0.00      0.00        21
                           kidney interstitial fibroblast       0.04      0.01      0.02       270
kidney loop of Henle thick ascending limb epithelial cell       0.67      0.62      0.64      2014
        kidney proximal convoluted tubule epithelial cell       0.60      0.60      0.60      8716
                                                leukocyte       0.23      0.11      0.15      3956
                                               macrophage       0.05      0.01      0.01       552
                             macula densa epithelial cell       0.00      0.00      0.00        19
                                           mesangial cell       0.00      0.00      0.00        31
                                                 podocyte       0.03      0.01      0.01       133

                                                 accuracy                           0.46     24853
                                                macro avg       0.17      0.15      0.15     24853
                                             weighted avg       0.43      0.46      0.43     24853

In [14]:

import pandas as pd
import os
import re

# 当前 Notebook 文件名
notebook_name = "slide_seq_mouse_kidney_PCA_42.ipynb"

# 初始化需要打印的值
init_train_loss = train_losses[0] if 'train_losses' in globals() else None
init_val_loss = val_losses[0] if 'val_losses' in globals() else None
converged_epoch = len(train_losses) - patience if 'train_losses' in globals() else None
converged_val_loss = best_val_loss if 'best_val_loss' in globals() else None

# 打印所有所需的指标
print("Metrics Summary:")
if 'train_losses' in globals():
    print(f"init_train_loss\tinit_val_loss\tconverged_epoch\tconverged_val_loss\tmacro_f1\tweighted_f1\tmicor_f1")
    print(f"{init_train_loss:.3f}\t{init_val_loss:.3f}\t{converged_epoch}\t{converged_val_loss:.3f}\t{macro_f1:.3f}\t{f1:.3f}\t{accuracy:.3f}")
else:
    print(f"macro_f1\tweighted_f1\tmicor_f1")
    print(f"{macro_f1:.3f}\t{f1:.3f}\t{accuracy:.3f}")

# 保存结果到 CSV 文件
output_data = {
    'dataset_split_random_seed': [int(random_seed)],
    'dataset': ['slide_seq_mouse_kidney'],
    'method': [re.search(r'kidney_(.*?)_\d+', notebook_name).group(1)],
    'init_train_loss': [init_train_loss if init_train_loss is not None else ''],
    'init_val_loss': [init_val_loss if init_val_loss is not None else ''],
    'converged_epoch': [converged_epoch if converged_epoch is not None else ''],
    'converged_val_loss': [converged_val_loss if converged_val_loss is not None else ''],
    'macro_f1': [macro_f1],
    'weighted_f1': [f1],
    'micor_f1': [accuracy]
}
output_df = pd.DataFrame(output_data)

# 保存到当前目录下名为 results 的文件夹中
if not os.path.exists('results'):
    os.makedirs('results')

csv_filename = f"results/{os.path.splitext(notebook_name)[0]}_results.csv"
output_df.to_csv(csv_filename, index=False)

Metrics Summary:
macro_f1	weighted_f1	micor_f1
0.155	0.433	0.457