In [1]:
import scanpy as sc
data_dir = '../../dataset/Marshall2022High_mouse_sampled.h5ad'
adata = sc.read_h5ad(data_dir)

In [2]:
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)

In [3]:
adata.var['gene_id'] = adata.var.index
adata.var.index = adata.var['gene_name']

# 输出 adata.var
adata.var

,feature_is_filtered,feature_reference,feature_biotype,feature_name-0,feature_length-0,feature_type-0,feature_name-1,feature_length-1,feature_type-1,feature_name-2,...,feature_length-5,feature_type-5,feature_name-6,feature_length-6,feature_type-6,feature_name-7,feature_length-7,feature_type-7,gene_name,gene_id
gene_name,,,,,,,,,,,,,,,,,,,,,
Erg28,False,NCBITaxon:10090,gene,Erg28,696,protein_coding,Erg28,696,protein_coding,Erg28,...,696,protein_coding,Erg28,696,protein_coding,Erg28,696,protein_coding,Erg28,ENSMUSG00000021252
0610009B22Rik,False,NCBITaxon:10090,gene,0610009B22Rik,852,protein_coding,0610009B22Rik,852,protein_coding,0610009B22Rik,...,852,protein_coding,0610009B22Rik,852,protein_coding,0610009B22Rik,852,protein_coding,0610009B22Rik,ENSMUSG00000007777
0610009E02Rik,False,NCBITaxon:10090,gene,0610009E02Rik,981,lncRNA,0610009E02Rik,981,lncRNA,0610009E02Rik,...,981,lncRNA,0610009E02Rik,981,lncRNA,0610009E02Rik,981,lncRNA,0610009E02Rik,ENSMUSG00000086714
0610009L18Rik,False,NCBITaxon:10090,gene,0610009L18Rik,639,lncRNA,0610009L18Rik,639,lncRNA,0610009L18Rik,...,639,lncRNA,0610009L18Rik,639,lncRNA,0610009L18Rik,639,lncRNA,0610009L18Rik,ENSMUSG00000043644
Dele1,False,NCBITaxon:10090,gene,Dele1,2394,protein_coding,Dele1,2394,protein_coding,Dele1,...,2394,protein_coding,Dele1,2394,protein_coding,Dele1,2394,protein_coding,Dele1,ENSMUSG00000024442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mt-Tm,False,NCBITaxon:10090,gene,mt-Tm,69,Mt_tRNA,mt-Tm,69,Mt_tRNA,mt-Tm,...,69,Mt_tRNA,mt-Tm,69,Mt_tRNA,mt-Tm,69,Mt_tRNA,mt-Tm,ENSMUSG00000064344
mt-Tp,False,NCBITaxon:10090,gene,mt-Tp,67,Mt_tRNA,mt-Tp,67,Mt_tRNA,mt-Tp,...,67,Mt_tRNA,mt-Tp,67,Mt_tRNA,mt-Tp,67,Mt_tRNA,mt-Tp,ENSMUSG00000064372
mt-Tq,False,NCBITaxon:10090,gene,mt-Tq,71,Mt_tRNA,mt-Tq,71,Mt_tRNA,mt-Tq,...,71,Mt_tRNA,mt-Tq,71,Mt_tRNA,mt-Tq,71,Mt_tRNA,mt-Tq,ENSMUSG00000064343
mt-Tt,False,NCBITaxon:10090,gene,mt-Tt,67,Mt_tRNA,mt-Tt,67,Mt_tRNA,mt-Tt,...,67,Mt_tRNA,mt-Tt,67,Mt_tRNA,mt-Tt,67,Mt_tRNA,mt-Tt,ENSMUSG00000064371
mt-Tv,False,NCBITaxon:10090,gene,mt-Tv,69,Mt_tRNA,mt-Tv,69,Mt_tRNA,mt-Tv,...,69,Mt_tRNA,mt-Tv,69,Mt_tRNA,mt-Tv,69,Mt_tRNA,mt-Tv,ENSMUSG00000064338

In [4]:
import scanpy as sc
import torch
import lightning.pytorch as pl
from self_supervision.models.lightning_modules.cellnet_autoencoder import MLPAutoEncoder
from self_supervision.estimator.cellnet import EstimatorAutoEncoder

# 设置你的 .ckpt 文件路径
ckpt_path = "../../sc_pretrained/Pretrained Models/RandomMask.ckpt"

# 模型参数
units_encoder = [512, 512, 256, 256, 64]
units_decoder = [256, 256, 512, 512]

# 初始化 EstimatorAutoEncoder 实例
estim = EstimatorAutoEncoder(data_path=None)  # 如果没有实际数据路径，可以设置为None

# 加载预训练模型
estim.model = MLPAutoEncoder.load_from_checkpoint(
    ckpt_path,
    gene_dim=19331,  # 根据你的数据调整
    batch_size=128,  # 根据你的需要调整
    units_encoder=units_encoder, 
    units_decoder=units_decoder,
    masking_strategy="random",  # 假设模型使用了随机掩码
    masking_rate=0.5,  # 根据需要调整
)

# 使用 GPU 进行评估（如果可用）
estim.trainer = pl.Trainer(accelerator="gpu", devices=1 if torch.cuda.is_available() else None)
estim.model

/home/hanchuangyi/miniconda3/envs/ssl/lib/python3.10/site-packages/merlin/dtypes/mappings/tf.py:52: UserWarning: Tensorflow dtype mappings did not load successfully due to an error: No module named 'tensorflow'
  warn(f"Tensorflow dtype mappings did not load successfully due to an error: {exc.msg}")
/home/hanchuangyi/miniconda3/envs/ssl/lib/python3.10/site-packages/merlin/dtypes/mappings/triton.py:53: UserWarning: Triton dtype mappings did not load successfully due to an error: No module named 'tritonclient'
  warn(f"Triton dtype mappings did not load successfully due to an error: {exc.msg}")

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

HPU available: False, using: 0 HPUs

MLPAutoEncoder(
  (train_metrics): MetricCollection(
    (explained_var_uniform): ExplainedVariance()
    (explained_var_weighted): ExplainedVariance()
    (mse): MeanSquaredError(),
    prefix=train_
  )
  (val_metrics): MetricCollection(
    (explained_var_uniform): ExplainedVariance()
    (explained_var_weighted): ExplainedVariance()
    (mse): MeanSquaredError(),
    prefix=val_
  )
  (test_metrics): MetricCollection(
    (explained_var_uniform): ExplainedVariance()
    (explained_var_weighted): ExplainedVariance()
    (mse): MeanSquaredError(),
    prefix=test_
  )
  (encoder): MLP(
    (0): Linear(in_features=19331, out_features=512, bias=True)
    (1): SELU()
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=512, out_features=512, bias=True)
    (4): SELU()
    (5): Dropout(p=0.1, inplace=False)
    (6): Linear(in_features=512, out_features=256, bias=True)
    (7): SELU()
    (8): Dropout(p=0.1, inplace=False)
    (9): Linear(in_features=256, out_features=256, bias=True)
    (10): SELU()
    (11): Dropout(p=0.1, inplace=False)
    (12): Linear(in_features=256, out_features=64, bias=True)
  )
  (decoder): Sequential(
    (0): MLP(
      (0): Linear(in_features=64, out_features=256, bias=True)
      (1): SELU()
      (2): Dropout(p=0.1, inplace=False)
      (3): Linear(in_features=256, out_features=256, bias=True)
      (4): SELU()
      (5): Dropout(p=0.1, inplace=False)
      (6): Linear(in_features=256, out_features=512, bias=True)
      (7): SELU()
      (8): Dropout(p=0.1, inplace=False)
      (9): Linear(in_features=512, out_features=512, bias=True)
      (10): SELU()
      (11): Dropout(p=0.1, inplace=False)
      (12): Linear(in_features=512, out_features=19331, bias=True)
    )
    (1): Sigmoid()
  )
)

In [5]:
import pandas as pd
var_df = pd.read_parquet('../../sc_pretrained/var.parquet')
var_df

            feature_id feature_name
0      ENSG00000186092        OR4F5
1      ENSG00000284733       OR4F29
2      ENSG00000284662       OR4F16
3      ENSG00000187634       SAMD11
4      ENSG00000188976        NOC2L
...                ...          ...
19326  ENSG00000288702       UGT1A3
19327  ENSG00000288705       UGT1A5
19328  ENSG00000182484       WASH6P
19329  ENSG00000288622   PDCD6-AHRR
19330  ENSG00000285815  GET1-SH3BGR

[19331 rows x 2 columns]

In [6]:
all_genes = var_df['feature_name'].tolist()
all_genes

['OR4F5',
 'OR4F29',
 'OR4F16',
 'SAMD11',
 'NOC2L',
 'KLHL17',
 'PLEKHN1',
 'PERM1',
 'HES4',
 'ISG15',
 'AGRN',
 'RNF223',
 'C1orf159',
 'TTLL10',
 'TNFRSF18',
 'TNFRSF4',
 'SDF4',
 'B3GALT6',
 'C1QTNF12',
 'UBE2J2',
 'SCNN1D',
 'ACAP3',
 'PUSL1',
 'INTS11',
 'CPTP',
 'TAS1R3',
 'DVL1',
 'MXRA8',
 'AURKAIP1',
 'CCNL2',
 'MRPL20',
 'ANKRD65',
 'TMEM88B',
 'VWA1',
 'ATAD3C',
 'ATAD3B',
 'ATAD3A',
 'TMEM240',
 'SSU72',
 'FNDC10',
 'MIB2',
 'MMP23B',
 'CDK11B',
 'SLC35E2B',
 'CDK11A',
 'NADK',
 'GNB1',
 'CALML6',
 'TMEM52',
 'CFAP74',
 'GABRD',
 'PRKCZ',
 'FAAP20',
 'SKI',
 'MORN1',
 'RER1',
 'PEX10',
 'PLCH2',
 'PANK4',
 'HES5',
 'TNFRSF14',
 'PRXL2B',
 'MMEL1',
 'TTC34',
 'ACTRT2',
 'PRDM16',
 'ARHGEF16',
 'MEGF6',
 'TPRG1L',
 'WRAP73',
 'TP73',
 'CCDC27',
 'SMIM1',
 'LRRC47',
 'CEP104',
 'DFFB',
 'C1orf174',
 'AJAP1',
 'NPHP4',
 'KCNAB2',
 'CHD5',
 'RPL22',
 'RNF207',
 'ICMT',
 'HES3',
 'GPR153',
 'ACOT7',
 'HES2',
 'ESPN',
 'TNFRSF25',
 'PLEKHG5',
 'NOL9',
 'TAS1R1',
 'ZBTB48',
 'KLHL21',
 'PHF13',
 'THAP3',
 'DNAJC11',
 'CAMTA1',
 'VAMP3',
 'PER3',
 'UTS2',
 'TNFRSF9',
 'PARK7',
 'ERRFI1',
 'SLC45A1',
 'RERE',
 'ENO1',
 'CA6',
 'SLC2A7',
 'SLC2A5',
 'GPR157',
 'H6PD',
 'SPSB1',
 'SLC25A33',
 'TMEM201',
 'PIK3CD',
 'CLSTN1',
 'CTNNBIP1',
 'LZIC',
 'NMNAT1',
 'RBP7',
 'UBE4B',
 'KIF1B',
 'PGD',
 'CENPS',
 'CORT',
 'DFFA',
 'PEX14',
 'CASZ1',
 'C1orf127',
 'TARDBP',
 'MASP2',
 'SRM',
 'EXOSC10',
 'MTOR',
 'ANGPTL7',
 'UBIAD1',
 'DISP3',
 'FBXO2',
 'FBXO44',
 'FBXO6',
 'MAD2L2',
 'DRAXIN',
 'AGTRAP',
 'C1orf167',
 'MTHFR',
 'CLCN6',
 'NPPA',
 'NPPB',
 'KIAA2013',
 'PLOD1',
 'MFN2',
 'MIIP',
 'TNFRSF8',
 'TNFRSF1B',
 'VPS13D',
 'DHRS3',
 'AADACL4',
 'AADACL3',
 'C1orf158',
 'PRAMEF12',
 'PRAMEF1',
 'PRAMEF11',
 'HNRNPCL1',
 'PRAMEF2',
 'PRAMEF4',
 'PRAMEF10',
 'PRAMEF7',
 'PRAMEF6',
 'PRAMEF27',
 'HNRNPCL3',
 'PRAMEF25',
 'HNRNPCL2',
 'PRAMEF26',
 'HNRNPCL4',
 'PRAMEF9',
 'PRAMEF13',
 'PRAMEF18',
 'PRAMEF5',
 'PRAMEF8',
 'PRAMEF33',
 'PRAMEF15',
 'PRAMEF14',
 'PRAMEF19',
 'PRAMEF17',
 'PRAMEF20',
 'LRRC38',
 'PDPN',
 'PRDM2',
 'KAZN',
 'TMEM51',
 'FHAD1',
 'EFHD2',
 'CTRC',
 'CELA2A',
 'CELA2B',
 'CASP9',
 'DNAJC16',
 'AGMAT',
 'DDI2',
 'RSC1A1',
 'PLEKHM2',
 'SLC25A34',
 'TMEM82',
 'FBLIM1',
 'UQCRHL',
 'SPEN',
 'ZBTB17',
 'SRARP',
 'HSPB7',
 'CLCNKA',
 'CLCNKB',
 'FAM131C',
 'EPHA2',
 'ARHGEF19',
 'CPLANE2',
 'FBXO42',
 'SZRD1',
 'SPATA21',
 'NECAP2',
 'NBPF1',
 'CROCC',
 'MFAP2',
 'ATP13A2',
 'SDHB',
 'PADI2',
 'PADI1',
 'PADI3',
 'PADI4',
 'PADI6',
 'RCC2',
 'ARHGEF10L',
 'ACTL8',
 'IGSF21',
 'KLHDC7A',
 'PAX7',
 'TAS1R2',
 'ALDH4A1',
 'IFFO2',
 'UBR4',
 'EMC1',
 'MRTO4',
 'AKR7A3',
 'AKR7A2',
 'SLC66A1',
 'CAPZB',
 'MICOS10',
 'NBL1',
 'HTR6',
 'TMCO4',
 'RNF186',
 'OTUD3',
 'PLA2G2E',
 'PLA2G2A',
 'PLA2G5',
 'PLA2G2D',
 'PLA2G2F',
 'PLA2G2C',
 'UBXN10',
 'VWA5B1',
 'CAMK2N1',
 'MUL1',
 'FAM43B',
 'CDA',
 'PINK1',
 'DDOST',
 'KIF17',
 'SH2D5',
 'HP1BP3',
 'EIF4G3',
 'ECE1',
 'NBPF3',
 'ALPL',
 'RAP1GAP',
 'USP48',
 'LDLRAD2',
 'HSPG2',
 'CELA3B',
 'CELA3A',
 'CDC42',
 'WNT4',
 'ZBTB40',
 'EPHA8',
 'C1QA',
 'C1QC',
 'C1QB',
 'EPHB2',
 'LACTBL1',
 'TEX46',
 'KDM1A',
 'LUZP1',
 'HTR1D',
 'HNRNPR',
 'ZNF436',
 'TCEA3',
 'ASAP3',
 'E2F2',
 'ID3',
 'RPL11',
 'ELOA',
 'PITHD1',
 'LYPLA2',
 'GALE',
 'HMGCL',
 'FUCA1',
 'CNR2',
 'PNRC2',
 'SRSF10',
 'MYOM3',
 'IL22RA1',
 'IFNLR1',
 'GRHL3',
 'STPG1',
 'NIPAL3',
 'RCAN3',
 'NCMAP',
 'SRRM1',
 'CLIC4',
 'RUNX3',
 'SYF2',
 'RSRP1',
 'RHD',
 'TMEM50A',
 'RHCE',
 'MACO1',
 'LDLRAP1',
 'MAN1C1',
 'SELENON',
 'MTFR1L',
 'AUNIP',
 'PAQR7',
 'STMN1',
 'PAFAH2',
 'EXTL1',
 'SLC30A2',
 'TRIM63',
 'PDIK1L',
 'FAM110D',
 'C1orf232',
 'ZNF593OS',
 'ZNF593',
 'CNKSR1',
 'CATSPER4',
 'CEP85',
 'SH3BGRL3',
 'UBXN11',
 'CD52',
 'CRYBG2',
 'ZNF683',
 'LIN28A',
 'DHDDS',
 'HMGN2',
 'RPS6KA1',
 'ARID1A',
 'PIGV',
 'ZDHHC18',
 'SFN',
 'GPN2',
 'GPATCH3',
 'NUDC',
 'NR0B2',
 'KDF1',
 'TRNP1',
 'TENT5B',
 'SLC9A1',
 'WDTC1',
 'TMEM222',
 'SYTL1',
 'MAP3K6',
 'FCN3',
 'CD164L2',
 'GPR3',
 'WASF2',
 'AHDC1',
 'FGR',
 'IFI6',
 'FAM76A',
 'STX12',
 'PPP1R8',
 'THEMIS2',
 'RPA2',
 'SMPDL3B',
 'XKR8',
 'EYA3',
 'PTAFR',
 'DNAJC8',
 'ATP5IF1',
 'SESN2',
 'MED18',
 'PHACTR4',
 'RCC1',
 'TRNAU1AP',
 'TAF12',
 'RAB42',
 'GMEB1',
 'YTHDF2',
 'OPRD1',
 'EPB41',
 'TMEM200B',
 'SRSF4',
 'MECR',
 'PTPRU',
 'MATN1',
 'LAPTM5',
 'SDC3',
 'PUM1',
 'NKAIN1',
 'SNRNP40',
 'ZCCHC17',
 'FABP3',
 'SERINC2',
 'TINAGL1',
 'HCRTR1',
 'PEF1',
 'COL16A1',
 'ADGRB2',
 'SPOCD1',
 'PTP4A2',
 'KHDRBS1',
 'TMEM39B',
 'KPNA6',
 'TXLNA',
 'CCDC28B',
 'IQCC',
 'DCDC2B',
 'TMEM234',
 'EIF3I',
 'FAM167B',
 'LCK',
 'HDAC1',
 'MARCKSL1',
 'TSSK3',
 'FAM229A',
 'BSDC1',
 'ZBTB8B',
 'ZBTB8A',
 'ZBTB8OS',
 'RBBP4',
 'SYNC',
 'KIAA1522',
 'YARS1',
 'S100PBP',
 'FNDC5',
 'HPCA',
 'TMEM54',
 'RNF19B',
 'AK2',
 'AZIN2',
 'TRIM62',
 'ZNF362',
 'A3GALT2',
 'PHC2',
 'ZSCAN20',
 'CSMD2',
 'HMGB4',
 'C1orf94',
 'SMIM12',
 'GJB5',
 'GJB4',
 'GJB3',
 'GJA4',
 'DLGAP3',
 'TMEM35B',
 'ZMYM6',
 'ZMYM1',
 'SFPQ',
 'ZMYM4',
 'KIAA0319L',
 'NCDN',
 'TFAP2E',
 'PSMB2',
 'C1orf216',
 'CLSPN',
 'AGO4',
 'AGO1',
 'AGO3',
 'TEKT2',
 'ADPRS',
 'COL8A2',
 'TRAPPC3',
 'MAP7D1',
 'THRAP3',
 'SH3D21',
 'EVA1B',
 'STK40',
 'LSM10',
 'OSCP1',
 'MRPS15',
 'CSF3R',
 'GRIK3',
 'ZC3H12A',
 'MEAF6',
 'SNIP1',
 'DNALI1',
 'GNL2',
 'RSPO1',
 'C1orf109',
 'CDCA8',
 'EPHA10',
 'MANEAL',
 'YRDC',
 'C1orf122',
 'MTF1',
 'INPP5B',
 'SF3A3',
 'FHL3',
 'UTP11',
 'POU3F1',
 'RRAGC',
 'MYCBP',
 'GJA9',
 'RHBDL2',
 'AKIRIN1',
 'NDUFS5',
 'MACF1',
 'BMP8A',
 'PABPC4',
 'HEYL',
 'NT5C1A',
 'HPCAL4',
 'PPIE',
 'BMP8B',
 'OXCT2',
 'TRIT1',
 'MYCL',
 'MFSD2A',
 'CAP1',
 'PPT1',
 'RLF',
 'TMCO2',
 'ZMPSTE24',
 'COL9A2',
 'SMAP2',
 'ZFP69B',
 'ZFP69',
 'EXO5',
 'ZNF684',
 'RIMS3',
 'NFYC',
 'KCNQ4',
 'CITED4',
 'CTPS1',
 'SLFNL1',
 'SCMH1',
 'FOXO6',
 'EDN2',
 'HIVEP3',
 'GUCA2B',
 'GUCA2A',
 'FOXJ3',
 'RIMKLA',
 'ZMYND12',
 'PPCS',
 'CCDC30',
 'PPIH',
 'YBX1',
 'CLDN19',
 'P3H1',
 'C1orf50',
 'TMEM269',
 'SVBP',
 'ERMAP',
 'ZNF691',
 'SLC2A1',
 'FAM183A',
 'EBNA1BP2',
 'CFAP57',
 'TMEM125',
 'C1orf210',
 'TIE1',
 'MPL',
 'CDC20',
 'ELOVL1',
 'MED8',
 'SZT2',
 'HYI',
 'PTPRF',
 'KDM4A',
 'ST3GAL3',
 'ARTN',
 'IPO13',
 'DPH2',
 'ATP6V0B',
 'B4GALT2',
 'CCDC24',
 'SLC6A9',
 'KLF17',
 'KLF18',
 'DMAP1',
 'ERI3',
 'RNF220',
 'TMEM53',
 'ARMH1',
 'KIF2C',
 'RPS8',
 'BEST4',
 'PLK3',
 'DYNLT4',
 'BTBD19',
 'PTCH2',
 'EIF2B3',
 'HECTD3',
 'UROD',
 'ZSWIM5',
 'HPDL',
 'MUTYH',
 'TOE1',
 'TESK2',
 'CCDC163',
 'MMACHC',
 'PRDX1',
 'AKR1A1',
 'NASP',
 'CCDC17',
 'GPBP1L1',
 'TMEM69',
 'IPP',
 'MAST2',
 'PIK3R3',
 'TSPAN1',
 'P3R3URF',
 'POMGNT1',
 'LURAP1',
 'RAD54L',
 'LRRC41',
 'UQCRH',
 'NSUN4',
 'FAAH',
 'DMBX1',
 'TMEM275',
 'KNCN',
 'MKNK1',
 'MOB3C',
 'ATPAF1',
 'TEX38',
 'EFCAB14',
 'CYP4B1',
 'CYP4A11',
 'CYP4X1',
 'CYP4Z1',
 'CYP4A22',
 'PDZK1IP1',
 'TAL1',
 'STIL',
 'CMPK1',
 'FOXE3',
 'FOXD2',
 'TRABD2B',
 'SLC5A9',
 'SPATA6',
 'AGBL4',
 'BEND5',
 'ELAVL4',
 'DMRTA2',
 'FAF1',
 'CDKN2C',
 'C1orf185',
 'RNF11',
 'TTC39A',
 'EPS15',
 'OSBPL9',
 'NRDC',
 'RAB3B',
 'TXNDC12',
 'KTI12',
 'BTF3L4',
 'ZFYVE9',
 'CC2D1B',
 'ORC1',
 'PRPF38A',
 'TUT4',
 'GPX7',
 'SHISAL2A',
 'COA7',
 'ZYG11B',
 'ZYG11A',
 'ECHDC2',
 'SCP2',
 'PODN',
 'SLC1A7',
 'CPT2',
 'CZIB',
 'MAGOH',
 'LRP8',
 'DMRTB1',
 'GLIS1',
 'NDC1',
 'YIPF1',
 'DIO1',
 'HSPB11',
 'LRRC42',
 'LDLRAD1',
 'TMEM59',
 'TCEANC2',
 'CDCP2',
 'CYB5RL',
 'MRPL37',
 'SSBP3',
 'ACOT11',
 'FAM151A',
 'MROH7',
 'TTC4',
 'PARS2',
 'TTC22',
 'LEXM',
 'DHCR24',
 'TMEM61',
 'BSND',
 'PCSK9',
 'USP24',
 'PLPP3',
 'PRKAA2',
 'FYB2',
 'C8A',
 'C8B',
 'DAB1',
 'OMA1',
 'TACSTD2',
 'MYSM1',
 'JUN',
 'FGGY',
 'HOOK1',
 'CYP2J2',
 'C1orf87',
 'NFIA',
 'TM2D1',
 'PATJ',
 'L1TD1',
 'KANK4',
 'USP1',
 'DOCK7',
 'ANGPTL3',
 'ATG4C',
 'FOXD3',
 'ALG6',
 'ITGB3BP',
 'EFCAB7',
 'PGM1',
 'ROR1',
 'UBE2U',
 'CACHD1',
 'RAVER2',
 'JAK1',
 'AK4',
 'DNAJC6',
 'LEPROT',
 'LEPR',
 'PDE4B',
 'SGIP1',
 'DYNLT5',
 'INSL5',
 'DNAI4',
 'MIER1',
 'SLC35D1',
 'C1orf141',
 'IL23R',
 'IL12RB2',
 'SERBP1',
 'GADD45A',
 'GNG12',
 'DIRAS3',
 'WLS',
 'RPE65',
 'DEPDC1',
 'LRRC7',
 'LRRC40',
 'SRSF11',
 'ANKRD13C',
 'CTH',
 'PTGER3',
 'ZRANB2',
 'NEGR1',
 'LRRIQ3',
 'FPGT',
 'TNNI3K',
 'LRRC53',
 'ERICH3',
 'CRYZ',
 'TYW3',
 'LHX8',
 'SLC44A5',
 'ACADM',
 'RABGGTB',
 'MSH4',
 'ASB17',
 'ST6GALNAC3',
 'ST6GALNAC5',
 'PIGK',
 'AK5',
 'ZZZ3',
 'USP33',
 'MIGA1',
 'NEXN',
 'FUBP1',
 'DNAJB4',
 'GIPC2',
 'PTGFR',
 'IFI44L',
 'IFI44',
 'ADGRL4',
 'ADGRL2',
 'TTLL7',
 'PRKACB',
 'SAMD13',
 'DNASE2B',
 'RPF1',
 'GNG5',
 'SPATA1',
 'CTBS',
 'SSX2IP',
 'LPAR3',
 'MCOLN2',
 'DNAI3',
 'MCOLN3',
 'SYDE2',
 'C1orf52',
 'BCL10',
 'DDAH1',
 'CCN1',
 'ZNHIT6',
 'COL24A1',
 'ODF2L',
 'CLCA2',
 'CLCA1',
 'CLCA4',
 'SH3GLB1',
 'SELENOF',
 'HS2ST1',
 'LMO4',
 'PKN2',
 'GTF2B',
 'KYAT3',
 'RBMXL1',
 'GBP3',
 'GBP1',
 'GBP2',
 'GBP7',
 'GBP4',
 'GBP5',
 'GBP6',
 'LRRC8B',
 'LRRC8C',
 'LRRC8D',
 'ZNF326',
 'BARHL2',
 'ZNF644',
 'HFM1',
 'CDC7',
 'TGFBR3',
 'BRDT',
 'EPHX4',
 'SETSIP',
 'BTBD8',
 'C1orf146',
 'GLMN',
 'RPAP2',
 'GFI1',
 'EVI5',
 'RPL5',
 'DIPK1A',
 'MTF2',
 'TMED5',
 'CCDC18',
 'DR1',
 'FNBP1L',
 'BCAR3',
 'DNTTIP2',
 'GCLM',
 'ABCA4',
 'ARHGAP29',
 'ABCD3',
 'F3',
 'SLC44A3',
 'CNN3',
 'ALG14',
 'TLCD4',
 'RWDD3',
 'PTBP2',
 'DPYD',
 'SNX7',
 'PLPPR5',
 'PLPPR4',
 'PALMD',
 'FRRS1',
 'AGL',
 'SLC35A3',
 'MFSD14A',
 'SASS6',
 'TRMT13',
 'LRRC39',
 'DBT',
 'RTCA',
 'CDC14A',
 'GPR88',
 'VCAM1',
 'EXTL2',
 'SLC30A7',
 'DPH5',
 'S1PR1',
 'OLFM3',
 'COL11A1',
 'RNPC3',
 'AMY2B',
 'AMY2A',
 'AMY1A',
 'AMY1B',
 'AMY1C',
 'PRMT6',
 'NTNG1',
 'VAV3',
 'SLC25A24',
 'NBPF4',
 'NBPF6',
 'FAM102B',
 'HENMT1',
 'PRPF38B',
 'FNDC7',
 'STXBP3',
 'AKNAD1',
 'GPSM2',
 'CLCC1',
 'WDR47',
 'TAF13',
 'TMEM167B',
 'C1orf194',
 'ELAPOR1',
 'SARS1',
 'CELSR2',
 'PSRC1',
 'MYBPHL',
 'SORT1',
 'PSMA5',
 'SYPL2',
 'ATXN7L2',
 'CYB561D1',
 'AMIGO1',
 'GPR61',
 'GNAI3',
 'GNAT2',
 'AMPD2',
 'GSTM4',
 'GSTM2',
 'GSTM1',
 'GSTM5',
 'GSTM3',
 'EPS8L3',
 'CSF1',
 'AHCYL1',
 'STRIP1',
 'ALX3',
 'UBL4B',
 'SLC6A17',
 'KCNC4',
 'RBM15',
 'SLC16A4',
 'LAMTOR5',
 'PROK1',
 'KCNA10',
 'KCNA2',
 'KCNA3',
 'CD53',
 'LRIF1',
 'DRAM2',
 'CEPT1',
 'DENND2D',
 'CHI3L2',
 'CHIA',
 'PIFO',
 'OVGP1',
 'WDR77',
 'ATP5PB',
 'C1orf162',
 'TMIGD3',
 'ADORA3',
 'RAP1A',
 'INKA2',
 'DDX20',
 'KCND3',
 'CTTNBP2NL',
 'WNT2B',
 'ST7L',
 'CAPZA1',
 'MOV10',
 'RHOC',
 'PPM1J',
 'TAFA3',
 'SLC16A1',
 'LRIG2',
 'MAGI3',
 'PHTF1',
 'RSBN1',
 'PTPN22',
 'BCL2L15',
 'AP4B1',
 'DCLRE1B',
 'HIPK1',
 'OLFML3',
 'SYT6',
 'TRIM33',
 ...]

In [7]:
adata.var['gene_name']=adata.var.index
adata.var['gene_name']

gene_name
Erg28                    Erg28
0610009B22Rik    0610009B22Rik
0610009E02Rik    0610009E02Rik
0610009L18Rik    0610009L18Rik
Dele1                    Dele1
                     ...
mt-Tm                    mt-Tm
mt-Tp                    mt-Tp
mt-Tq                    mt-Tq
mt-Tt                    mt-Tt
mt-Tv                    mt-Tv
Name: gene_name, Length: 16661, dtype: category
Categories (20499, object): ['0610009B22Rik', '0610009E02Rik', '0610009L18Rik', '0610010K14Rik', ..., 'mt-Tq', 'mt-Ts2', 'mt-Tt', 'mt-Tv']

In [8]:
import numpy as np
# 初始化一个新的数据矩阵，形状为 (adata.X.shape[0], len(all_genes))，填充为零
new_data = np.zeros((adata.X.shape[0], len(all_genes)), dtype=np.float32)

In [9]:
existing_genes = adata.var['gene_name']
existing_genes

gene_name
Erg28                    Erg28
0610009B22Rik    0610009B22Rik
0610009E02Rik    0610009E02Rik
0610009L18Rik    0610009L18Rik
Dele1                    Dele1
                     ...
mt-Tm                    mt-Tm
mt-Tp                    mt-Tp
mt-Tq                    mt-Tq
mt-Tt                    mt-Tt
mt-Tv                    mt-Tv
Name: gene_name, Length: 16661, dtype: category
Categories (20499, object): ['0610009B22Rik', '0610009E02Rik', '0610009L18Rik', '0610010K14Rik', ..., 'mt-Tq', 'mt-Ts2', 'mt-Tt', 'mt-Tv']

In [10]:
# 将所有基因名称转换为小写
all_genes_lower = [gene.lower() for gene in all_genes]
adata_genes_lower = [gene.lower() for gene in existing_genes]

# 将两个列表转换为集合
all_genes_set = set(all_genes_lower)
adata_genes_set = set(adata_genes_lower)

# 计算交集
matching_genes = all_genes_set.intersection(adata_genes_set)
matching_count = len(matching_genes)
# 计算不匹配的基因
non_matching_genes = adata_genes_set - matching_genes
non_matching_count = len(non_matching_genes)


# 输出结果
print(f"匹配的基因数量: {matching_count}")
print(f"匹配的基因列表: {matching_genes}")
non_matching_genes

匹配的基因数量: 13074

{'b130046b21rik',
 'gm43274',
 'vmn2r103',
 'b630019k06rik',
 'apol7e',
 'trp53i13',
 'gm43136',
 '2010003k11rik',
 '4930453n24rik',
 'gm28863',
 'uqcc6',
 'gm43859',
 'gm27030',
 '4930520o04rik',
 'gm43482',
 'gm38336',
 '3110082i17rik',
 'gm10451',
 '1700067k01rik',
 'gm9755',
 'gm14399',
 '3300002i08rik',
 'gm4208',
 'gramd2',
 'a930001c03rik',
 'zfp235',
 'bc049762',
 'trp53inp2',
 '6720427i07rik',
 'ldc1',
 '3222401l13rik',
 'zfta',
 'gm20404',
 'h2bc27',
 '2610206c17rik',
 'ube2d2a',
 'a230065n10rik',
 'a230072e10rik',
 'slc7a12',
 '4930481b07rik',
 '3010003l21rik',
 'cyp2j8',
 'slfn9',
 'vmn1r4',
 'mir670hg',
 'gm4221',
 'notumos',
 'ifi207',
 'vdac3-ps1',
 'gm13427',
 'gm20422',
 'trac',
 'gm2164',
 'gm21972',
 '4833439l19rik',
 'gm9725',
 'gm11734',
 'slc22a19',
 'gm42447',
 'gm43336',
 'd630033o11rik',
 'zfp119b',
 'ifi204',
 'c630043f03rik',
 '4930594m22rik',
 'zfp354b',
 'dynlt1a',
 'gm17634',
 'gm20442',
 'gm6871',
 'tha1',
 'gm43618',
 'h3f3aos',
 'serpinb6a',
 'e130304i02rik',
 'd930048n14rik',
 'gm38380',
 'adam1a',
 'gm13205',
 'h2-d1',
 'pcdhb21',
 'gm37893',
 'zfp658',
 'hars',
 'cstpp1',
 'zfp513',
 'gm26594',
 'tex56',
 'gm15563',
 '3110009e18rik',
 'plet1os',
 'spin2c',
 '1700113a16rik',
 'c130026i21rik',
 '9130230l23rik',
 'il11ra1',
 '1700048o20rik',
 'zfp286',
 '2810002d19rik',
 'gm37860',
 'dnah7b',
 'gm42986',
 '1190005i06rik',
 'gm33206',
 'gm29107',
 'rab9',
 '1110018n20rik',
 'bc004004',
 'gm37401',
 'supt3',
 'gm15245',
 'gm29427',
 'gm15886',
 'gm20752',
 'a530013c23rik',
 '4930533i22rik',
 'gm14055',
 'gm26801',
 'atp5e',
 'gm37558',
 'gm38042',
 'gm42556',
 'zfp790',
 'platr21',
 'gucy2g',
 'pantr1',
 '2410004b18rik',
 'gm4524',
 'gm37470',
 'septin2_ensmusg00000026276',
 '1500009l16rik',
 '4631405j19rik',
 '4933406p04rik',
 'frmd8os',
 '1810010h24rik',
 'glt28d2',
 'gm42732',
 'gm26935',
 'chmp1b2',
 'ifi47',
 'gm16118',
 'gm16006',
 'gm6209',
 'gm38034',
 '4930579f01rik',
 'slco1a1',
 'lrrc51',
 'au022252',
 'mettl2',
 'gm27224',
 'gm45713',
 'gm8225',
 'ltb4r1',
 'gm20522',
 'supt4a',
 'zfp971',
 'gm49322',
 'gm38077',
 'gm19710',
 'gm38120',
 '9330198n18rik',
 'ai467606',
 'h2-eb1',
 'gm26533',
 'gm30667',
 'gm15246',
 '5930430l01rik',
 'tgtp1',
 'gm4419',
 'zfas1',
 'b430319g15rik',
 'gm37982',
 'gm17597',
 'clec2h',
 '6530409c15rik',
 'g730003c15rik',
 'c130013h08rik',
 'gm16741',
 'a230103j11rik',
 'gm38037',
 'tmem29',
 'gm43429',
 'yae1d1',
 '9530059o14rik',
 'zfp414',
 'nnt_ensmusg00000025453',
 'e030037k01rik',
 '9030624g23rik',
 '2310022b05rik',
 'gm38374',
 'h13',
 'gm7247',
 'gm43273',
 'gm37019',
 'ifi206',
 'bc006965',
 'gm17276',
 'zfp113',
 'zfp963',
 'gm38293',
 '9830144p21rik',
 'mir22hg',
 'gm15491',
 'zfp268',
 'gm5786',
 'zfp619',
 'gm10032',
 'gm10845',
 'gm6999',
 'gm5424',
 'gm17035',
 'a630072m18rik',
 'zfp811',
 'zfp866',
 'zfp810',
 'gm19325',
 'f930017d23rik',
 '1810017p11rik',
 'gm17494',
 'ai597479',
 'a',
 '9230116n13rik',
 'gm27252',
 'gm20324',
 'gm19719',
 'gm7030',
 'zfp108',
 'zfp143',
 '1700123m08rik',
 'gm11532',
 'gm38082',
 'mir181a-1hg',
 '1700030n03rik',
 'zfp68',
 'tmem45a2',
 '1700008o03rik',
 '1700034h15rik',
 '4930412m03rik',
 'gm15410',
 'zfp366',
 '1700086p04rik',
 '2010320m18rik',
 'dynlt2a2',
 'potegl',
 '2610528j11rik',
 'fam122a',
 'gstt2',
 'a930004d18rik',
 'gm37370',
 'gm26782',
 'd030047h15rik',
 'gm14027',
 'gm15932',
 'gm17690',
 'gm10778',
 'd8ertd738e',
 'gm42940',
 'gm42557',
 'gm12022',
 'fbxl21',
 'gm12592',
 'gm14812',
 'slc6a20b',
 'zfp60',
 'ms4a4b',
 '1700001g17rik',
 'zfp947',
 '1700112d23rik',
 'gm15506',
 'zfp960',
 'a530083i20rik',
 'gm14169',
 'gm43190',
 'zfp384',
 'zfp646',
 '1700006j14rik',
 'gm11627',
 'gm37314',
 'gm19684',
 'gm9484',
 '4921524j17rik',
 '9030607j07rik',
 'au021092',
 'gm42908',
 'zfp850',
 'gm37472',
 '9130008f23rik',
 'mir6236',
 'bc050972',
 'gm37474',
 'gm37403',
 'wdyhv1',
 'pals2',
 'zfp973',
 '2900026a02rik',
 'gm10062',
 'gm11775',
 'ccdc162',
 'gm7160',
 'gm42679',
 'b430010i23rik',
 'gm11789',
 'gm27253',
 '2610035d17rik',
 'isoc2b',
 'hba-a2',
 'gm15345',
 '4933439c10rik',
 'gm43571',
 '2610507i01rik',
 'gm42559',
 'gm15518',
 'gm16364_ensmusg00000086915',
 'e430021h15rik',
 'gm11837',
 'exoc3l',
 'zfp651',
 'gm26901',
 'gm11525',
 '9230111e07rik',
 'gm37524',
 '1700029j07rik',
 'gm14066',
 'zfp459',
 'gm26982',
 '2610044o15rik8',
 '4930586n03rik',
 'gm11476',
 'd630029k05rik',
 'zfp277',
 'zfp664',
 'gm6576',
 '2200002d01rik',
 'gm16564',
 'tmem191',
 'gm13483',
 'smpd5',
 'nopchap1',
 'gm37776',
 'gvin2',
 '3110045c21rik',
 '2310040g24rik',
 'gm19272',
 'b230307c23rik',
 'gm29242',
 'gm12999',
 '5830454e08rik',
 'gm17660',
 'atp5h',
 'gm26632',
 'gm37137',
 'gm28153',
 'b930095g15rik',
 'xntrpc',
 'snord3b-ps1_ensmusg00000064400',
 'gm14305',
 'gm42413',
 'gm15564',
 'gm13832',
 'gm10501',
 'gm16740',
 'gm38300',
 'gm13219',
 'iglc3',
 '1810009a15rik',
 'brip1os',
 'c030014i23rik',
 'gars',
 'gm26555',
 'gm28055',
 'zfp871',
 'e130114p18rik',
 'bc035044',
 'h1f0',
 'gm12596',
 'gm43544',
 'gm38224',
 'lrrc55os',
 'csf2rb2',
 '2610027k06rik',
 'pierce2',
 'zfp511',
 '9930104l06rik',
 'timm8a1',
 '2310014f06rik',
 'zfp275',
 'zfp13',
 'ai839979',
 'gm807',
 'lhfp',
 'zfp770',
 'lhx1os',
 'zfp712',
 '2700062c07rik',
 'gm38111',
 'zfp870',
 'nr6a1os',
 'gm28036',
 'gm43457',
 'gm38014',
 'zfp446',
 'zfp39',
 'gm10130',
 'gm28376',
 'gm43260',
 'nupr1l',
 'gm37988',
 'spacdr',
 'gm43808',
 '1700007l15rik',
 'lncob1',
 'dnaaf9',
 '6720475m21rik',
 '4933417c20rik',
 'mypopos',
 '2810404m03rik',
 'gm15535',
 'gm28875',
 'vars',
 'gm5547',
 'gm9847',
 '2700029l08rik',
 'gm37967',
 'gm14207',
 'gm43481',
 'gm42869',
 'ces2c',
 'serpina1b',
 'gm37303',
 'gm15832',
 'zfp938',
 'slc13a2os',
 '5730455p16rik',
 'be692007',
 'cn725425',
 '2010315b03rik',
 'tspan32os',
 'gm37409',
 'zfp334',
 '4933405d12rik',
 'dnah7c',
 'akr1c13',
 '5430420f09rik',
 '2310008n11rik',
 'bb365896',
 'ctla2b',
 'bvht',
 '6530401f13rik',
 'gm5577',
 'zfp804b',
 'gm15581',
 'gm16618',
 'gm3289',
 'gm43713',
 'il6ra',
 'gm26236',
 'gm38375',
 '8030442b05rik',
 'gm10555',
 '9330185c12rik',
 'gm32554',
 '6030400a10rik',
 'mfsd7a',
 'trp53inp1',
 'zfp263',
 'rdh7',
 'h2-aa',
 'gm14061',
 'gm11973',
 'gm13773',
 '1810062g17rik',
 'abca8a',
 'gm1976',
 'gm1604b',
 'f5_ensmusg00000026579',
 'gm13710',
 'gm37733',
 '2610037d02rik',
 'gm13974',
 '4933430i17rik',
 'mfsd4b1',
 'kctd12b',
 'ai506816',
 'zfp219',
 'cyp4a10',
 'zfp560',
 'gm37621',
 'fbxw17',
 'gm11520',
 'ces2g',
 'gm37390',
 'gm9903',
 'a730049h05rik',
 'd930032p07rik',
 'gm29570',
 'gm15756',
 'themis3',
 'zfp808',
 'gm37606',
 '6230400d17rik',
 'gm42460',
 'gm8730',
 'firre',
 'upk3bl',
 '2010001a14rik',
 'gm17244',
 'cyp2f2',
 'arf2',
 'gm16251',
 'gm20646',
 'gm43860',
 'gm15663',
 'a330008l17rik',
 '5730480h06rik',
 '4931414p19rik',
 'gm29642',
 'gm37728',
 'a430018g15rik',
 'gm3383',
 'eno1b',
 'gm17501',
 'gm42636',
 'gm42775',
 'a730017l22rik',
 'gm15879',
 'f3_ensmusg00000028128',
 'slc35e2',
 '2310057m21rik',
 'rapgef4os1',
 'zfp711',
 'gm43652',
 'mterf1a',
 'zfp599',
 'gm266',
 'av039307',
 'gm43154',
 'bb014433',
 'gm37820',
 'spg20',
 'zkscan17',
 'rwdd4a',
 'ai854703',
 'trp53i11',
 'sectm1a',
 'd630044l22rik',
 'irx3os',
 'gm38056',
 'zfp395',
 'gm10638',
 'phtf1os',
 '4930518i15rik',
 '2600014e21rik',
 'gm37954',
 'hdac1-ps',
 'mt-tv',
 'zfp383',
 'mt-tm',
 'gm26815',
 '4732463b04rik',
 'gm42841',
 'gm12940',
 'gm29611',
 'gm7102',
 'gm15441',
 'cntnap5b',
 'h2-ab1',
 'gm43143',
 '5930403n24rik',
 'gm42544',
 'snhg9',
 'tcte2',
 '1700101i11rik',
 'gm28374',
 'gm16279',
 'gm13412',
 'zrsr1',
 'zfp358',
 '1700081b01rik',
 'mfap1b',
 '4930515g01rik',
 'a230004m16rik',
 'gm40348',
 'gm13166',
 'ms4a4d',
 'gm43508',
 '5830487j09rik',
 '1810037i17rik',
 'zfp764',
 'igtp',
 '2610306m01rik',
 'd030056l22rik',
 'e230013l22rik',
 'zfp772',
 'gm38319',
 'gm6793',
 'gm42892',
 'gm4787',
 'zfp598',
 'defb19',
 'gm37064',
 'zfp553',
 'gm15510',
 'gm12648',
 '1110025m09rik',
 'gm17251',
 'h2-ob',
 'adrm1b',
 'gm11337',
 'serpinb6b',
 'ai504432',
 '1810041h14rik',
 'man2c1os',
 'gm42432',
 'gm14963',
 'gm28526',
 'gm38021',
 'gm26779',
 'gm13778',
 'hbb-bs',
 'mir6240',
 'd130017n08rik',
 'morrbid',
 'gm27010',
 'abca8b',
 '9430034n14rik',
 'gm15958',
 'oip5os1',
 'c79798',
 'nlrp4c',
 'gm11457',
 'uqcc5',
 'b430218f22rik',
 'atosa',
 'gm37529',
 'tmem167',
 'phf11d',
 '4732491k20rik',
 'd430041d05rik',
 'trp73',
 'abhd11os',
 '2510017j16rik',
 'gm19412',
 'gm14102',
 'gm17382',
 '4933431e20rik',
 'gm32569',
 'gm37742',
 'oacyl',
 'a430027c01rik',
 'gm12762',
 'gm6410',
 'car7',
 'zfp568',
 'naa12',
 'gm26588',
 'zfp729a',
 'a330033j07rik',
 'gm16069',
 'pbld2',
 'ofcc1',
 'slco1a4',
 'f830016b08rik',
 'gm43545',
 '1810024b03rik',
 'zfp758',
 '4930444p10rik',
 'zfp612',
 'zfp281',
 'cd24a',
 'gm16863',
 '2500004c02rik',
 'nat8f1',
 'atp6ap1l',
 'bglap3',
 'gm16010',
 '4932412d23rik',
 '2610016a17rik',
 'gm42726',
 'entrep1',
 'gm16093',
 'gm29266',
 'zfp174',
 '4933431k23rik',
 'atad3aos',
 'gm38344',
 'gm10974',
 'gm43667',
 'gm17473',
 '1500004a13rik',
 'gm12216',
 'gm20528',
 'gm5432',
 'pam16l',
 'xist',
 '4930509e16rik',
 '4932411k12rik',
 'zfp280c',
 'e130102h24rik',
 'gm43379',
 'rps4l',
 'zfp524',
 'gm21974',
 'gm8126',
 'slc22a28',
 'gm12326',
 'cldn34c1',
 'gm9754',
 '1700009j07rik',
 'rsph3b',
 'a530083m17rik',
 'gm26850',
 'gm15938',
 '4921539h07rik',
 'gm15866',
 'gm42979',
 'pcdhb22',
 'gm13421',
 'gm43609',
 'zfp768',
 'zfp472',
 '4931406c07rik',
 '5031425e22rik',
 '2810029c07rik',
 '4632428c04rik',
 'gm4876',
 'atp5g1',
 'supt5',
 'fbxw15',
 'bc065397',
 'a830019p07rik',
 'gm15983',
 'bfar_ensmusg00000022684',
 'gm37780',
 '0610040j01rik',
 'gm16163',
 '4833445i07rik',
 'gm38377',
 'depdc1a',
 'c130071c03rik',
 'gm6712',
 'atp5j2',
 'zfp217',
 'zfp622',
 '8030462n17rik',
 'gm15972',
 'gm43413',
 'fam122c',
 'gm10522',
 '2810408a11rik',
 'gm12744',
 'sardhos',
 'gm29609',
 '1110059g10rik',
 'zfp239',
 'gm37376',
 'mgl2',
 'ssu2',
 'gm12798',
 'd030025e07rik',
 'gm20186',
 'ces2e',
 '1700109h08rik',
 'zfp455',
 'd17h6s53e',
 'gm16066',
 'adam4',
 'i830077j02rik',
 'pierce1',
 '9130019p16rik',
 'gm8369',
 'car9',
 'gm11808',
 'zfp229',
 '4930509g22rik',
 'gm20268',
 '5430427n15rik',
 'gm37397',
 'gm13912',
 'd730003i15rik',
 'gm15343',
 'gm16833',
 'gm16091',
 'gm43387',
 'h3f3a',
 'gm17541',
 'gm43679',
 '9130230n09rik',
 'gm17399',
 'gm11696',
 'gm10433',
 'gm42600',
 'gm6598',
 'zbtb11os1',
 '9630010a21rik',
 'gm16343',
 'slfn8',
 'gm13830',
 'cyp4a31',
 '4833412k13rik',
 'gm42461',
 'trp63',
 '1700017b05rik',
 'trbc1',
 'mfap1a',
 'd3ertd751e',
 '4930532g15rik',
 '6330418k02rik',
 'tescl',
 'cyp4f17',
 'd630045j12rik',
 'a130051j06rik',
 'cyp4f14',
 'kitl',
 'gm16973',
 'c230096k16rik',
 'sox5os4',
 'pot1a',
 'g6pc',
 'gm16175',
 'gm17178',
 'igkc',
 'gm5113_ensmusg00000066647',
 '9030622o22rik',
 'd930020b18rik',
 'mt-tl1',
 'arhgap27os1',
 'casp12',
 'apol9a',
 'gm20755',
 'bc106179',
 'cspg4b',
 '4632427e13rik',
 'gm15473',
 'lipo3',
 'gm17491',
 'gm28037',
 'gm37144',
 'gm43566',
 'zfp706',
 'abca17',
 'gm10382',
 'kif4',
 'xndc1',
 'mzt2',
 'gm29292',
 '4921531c22rik',
 'gm13963',
 'ddit3_ensmusg00000025408',
 'gm10138',
 'gm16638',
 'd030068k23rik',
 'pycrl',
 'dubr',
 'alyref2',
 'b230219d22rik',
 'gm20476',
 'selenok-ps1',
 'gm20033',
 'zfp109',
 'gm42436',
 'gstm7',
 'gm16537',
 'zfp248',
 'gm3086',
 'zfp995',
 'bc035947',
 'gm14232',
 'gm8739',
 'gm10283',
 'dynlt1c',
 'zfp618',
 'gm13470',
 'c77080',
 'gm13479',
 'gm37206',
 'them7',
 'gm43081',
 'gm26739',
 'ifi211',
 'gm28229',
 'gm20390',
 'trp53rka',
 '4930426i24rik',
 '1810019d21rik',
 'atp5k',
 'gm42899',
 'gm42992',
 '1700012i11rik',
 'e030042o20rik',
 'nepn',
 '2510009e07rik',
 'gm15889',
 'rsl1',
 '2210408i21rik',
 'nars',
 '1300002e11rik',
 'a430073d23rik',
 '1700055d18rik',
 'aa474408',
 'pcdhb18',
 '1600023n17rik',
 'sirpb1b',
 'gm11613',
 'gm20443',
 'gm525',
 'gimap1os',
 'gm28539',
 'ggnbp1',
 'gm12474',
 'a730020e08rik',
 '4930432b10rik',
 'zfp746',
 'gm26805',
 'ank',
 'gm5106',
 '4930556j24rik',
 'ifi209',
 'mmgt2',
 '9130017k11rik',
 '9330162012rik',
 '4930556n13rik',
 'gm26861',
 '1110020a21rik',
 'bc031181',
 'gm21092',
 'gbp9',
 'gm20492',
 '0610043k17rik',
 '4933434e20rik',
 'nscme3l',
 'clec4a1',
 'gm10649',
 'akr1c20',
 'gm47854',
 'd230022j07rik',
 'gm43843',
 'zfp319',
 'zfp526',
 'gm38197',
 'gm43584',
 'gm26885',
 'gm42800',
 '4921515e04rik',
 'gm20532',
 'gm28529',
 'b130034c11rik',
 'gm15354',
 'gm14964',
 'gm42981',
 'gm3081',
 '4930554g24rik',
 'gm43088',
 'a530072m11rik',
 'akr1c19',
 'atp5b',
 'zfp937',
 'zfp931',
 'il4ra',
 'gm43668',
 '9330159m07rik',
 'zfp821',
 'gm10115',
 'ly6g6g',
 'gm10125',
 'gm43200',
 'hectd2os',
 'a430110c17rik',
 'zfp324',
 'gm37415',
 '9330151l19rik',
 'trgc4',
 'gm7265',
 'gstt3',
 'zfp558',
 'zfp563',
 '4921536k21rik',
 'catspere2',
 'mterf1b',
 'gm28156',
 '6720489n17rik',
 'mfsd4b3-ps_ensmusg00000071335',
 '4930523c07rik',
 'car12',
 'mt-tq',
 'gm26967',
 'gm43509',
 '4932422m17rik',
 'gm38392',
 'cd244a',
 '4930473a02rik',
 'gm15614',
 'gm49340',
 'b130024g19rik',
 'slfn5os',
 'prox1os',
 'zfp46',
 '4930470g03rik',
 'c79130',
 'gm14582',
 'pirb',
 ...}

In [11]:
gene_to_index = {gene: idx for idx, gene in enumerate(all_genes_lower)}
gene_to_index

{'or4f5': 0,
 'or4f29': 1,
 'or4f16': 2,
 'samd11': 3,
 'noc2l': 4,
 'klhl17': 5,
 'plekhn1': 6,
 'perm1': 7,
 'hes4': 8,
 'isg15': 9,
 'agrn': 10,
 'rnf223': 11,
 'c1orf159': 12,
 'ttll10': 13,
 'tnfrsf18': 14,
 'tnfrsf4': 15,
 'sdf4': 16,
 'b3galt6': 17,
 'c1qtnf12': 18,
 'ube2j2': 19,
 'scnn1d': 20,
 'acap3': 21,
 'pusl1': 22,
 'ints11': 23,
 'cptp': 24,
 'tas1r3': 25,
 'dvl1': 26,
 'mxra8': 27,
 'aurkaip1': 28,
 'ccnl2': 29,
 'mrpl20': 30,
 'ankrd65': 31,
 'tmem88b': 32,
 'vwa1': 33,
 'atad3c': 34,
 'atad3b': 35,
 'atad3a': 36,
 'tmem240': 37,
 'ssu72': 38,
 'fndc10': 39,
 'mib2': 40,
 'mmp23b': 41,
 'cdk11b': 42,
 'slc35e2b': 43,
 'cdk11a': 44,
 'nadk': 45,
 'gnb1': 46,
 'calml6': 47,
 'tmem52': 48,
 'cfap74': 49,
 'gabrd': 50,
 'prkcz': 51,
 'faap20': 52,
 'ski': 53,
 'morn1': 54,
 'rer1': 55,
 'pex10': 56,
 'plch2': 57,
 'pank4': 58,
 'hes5': 59,
 'tnfrsf14': 60,
 'prxl2b': 61,
 'mmel1': 62,
 'ttc34': 63,
 'actrt2': 64,
 'prdm16': 65,
 'arhgef16': 66,
 'megf6': 67,
 'tprg1l': 68,
 'wrap73': 69,
 'tp73': 70,
 'ccdc27': 71,
 'smim1': 72,
 'lrrc47': 73,
 'cep104': 74,
 'dffb': 75,
 'c1orf174': 76,
 'ajap1': 77,
 'nphp4': 78,
 'kcnab2': 79,
 'chd5': 80,
 'rpl22': 81,
 'rnf207': 82,
 'icmt': 83,
 'hes3': 84,
 'gpr153': 85,
 'acot7': 86,
 'hes2': 87,
 'espn': 88,
 'tnfrsf25': 89,
 'plekhg5': 90,
 'nol9': 91,
 'tas1r1': 92,
 'zbtb48': 93,
 'klhl21': 94,
 'phf13': 95,
 'thap3': 96,
 'dnajc11': 97,
 'camta1': 98,
 'vamp3': 99,
 'per3': 100,
 'uts2': 101,
 'tnfrsf9': 102,
 'park7': 103,
 'errfi1': 104,
 'slc45a1': 105,
 'rere': 106,
 'eno1': 107,
 'ca6': 108,
 'slc2a7': 109,
 'slc2a5': 110,
 'gpr157': 111,
 'h6pd': 112,
 'spsb1': 113,
 'slc25a33': 114,
 'tmem201': 115,
 'pik3cd': 116,
 'clstn1': 117,
 'ctnnbip1': 118,
 'lzic': 119,
 'nmnat1': 120,
 'rbp7': 121,
 'ube4b': 122,
 'kif1b': 123,
 'pgd': 124,
 'cenps': 125,
 'cort': 126,
 'dffa': 127,
 'pex14': 128,
 'casz1': 129,
 'c1orf127': 130,
 'tardbp': 131,
 'masp2': 132,
 'srm': 133,
 'exosc10': 134,
 'mtor': 135,
 'angptl7': 136,
 'ubiad1': 137,
 'disp3': 138,
 'fbxo2': 139,
 'fbxo44': 140,
 'fbxo6': 141,
 'mad2l2': 142,
 'draxin': 143,
 'agtrap': 144,
 'c1orf167': 145,
 'mthfr': 146,
 'clcn6': 147,
 'nppa': 148,
 'nppb': 149,
 'kiaa2013': 150,
 'plod1': 151,
 'mfn2': 152,
 'miip': 153,
 'tnfrsf8': 154,
 'tnfrsf1b': 155,
 'vps13d': 156,
 'dhrs3': 157,
 'aadacl4': 158,
 'aadacl3': 159,
 'c1orf158': 160,
 'pramef12': 161,
 'pramef1': 162,
 'pramef11': 163,
 'hnrnpcl1': 164,
 'pramef2': 165,
 'pramef4': 166,
 'pramef10': 167,
 'pramef7': 168,
 'pramef6': 169,
 'pramef27': 170,
 'hnrnpcl3': 171,
 'pramef25': 172,
 'hnrnpcl2': 173,
 'pramef26': 174,
 'hnrnpcl4': 175,
 'pramef9': 176,
 'pramef13': 177,
 'pramef18': 178,
 'pramef5': 179,
 'pramef8': 180,
 'pramef33': 181,
 'pramef15': 182,
 'pramef14': 183,
 'pramef19': 184,
 'pramef17': 185,
 'pramef20': 186,
 'lrrc38': 187,
 'pdpn': 188,
 'prdm2': 189,
 'kazn': 190,
 'tmem51': 191,
 'fhad1': 192,
 'efhd2': 193,
 'ctrc': 194,
 'cela2a': 195,
 'cela2b': 196,
 'casp9': 197,
 'dnajc16': 198,
 'agmat': 199,
 'ddi2': 200,
 'rsc1a1': 201,
 'plekhm2': 202,
 'slc25a34': 203,
 'tmem82': 204,
 'fblim1': 205,
 'uqcrhl': 206,
 'spen': 207,
 'zbtb17': 208,
 'srarp': 209,
 'hspb7': 210,
 'clcnka': 211,
 'clcnkb': 212,
 'fam131c': 213,
 'epha2': 214,
 'arhgef19': 215,
 'cplane2': 216,
 'fbxo42': 217,
 'szrd1': 218,
 'spata21': 219,
 'necap2': 220,
 'nbpf1': 221,
 'crocc': 222,
 'mfap2': 223,
 'atp13a2': 224,
 'sdhb': 225,
 'padi2': 226,
 'padi1': 227,
 'padi3': 228,
 'padi4': 229,
 'padi6': 230,
 'rcc2': 231,
 'arhgef10l': 232,
 'actl8': 233,
 'igsf21': 234,
 'klhdc7a': 235,
 'pax7': 236,
 'tas1r2': 237,
 'aldh4a1': 238,
 'iffo2': 239,
 'ubr4': 240,
 'emc1': 241,
 'mrto4': 242,
 'akr7a3': 243,
 'akr7a2': 244,
 'slc66a1': 245,
 'capzb': 246,
 'micos10': 247,
 'nbl1': 248,
 'htr6': 249,
 'tmco4': 250,
 'rnf186': 251,
 'otud3': 252,
 'pla2g2e': 253,
 'pla2g2a': 254,
 'pla2g5': 255,
 'pla2g2d': 256,
 'pla2g2f': 257,
 'pla2g2c': 258,
 'ubxn10': 259,
 'vwa5b1': 260,
 'camk2n1': 261,
 'mul1': 262,
 'fam43b': 263,
 'cda': 264,
 'pink1': 265,
 'ddost': 266,
 'kif17': 267,
 'sh2d5': 268,
 'hp1bp3': 269,
 'eif4g3': 270,
 'ece1': 271,
 'nbpf3': 272,
 'alpl': 273,
 'rap1gap': 274,
 'usp48': 275,
 'ldlrad2': 276,
 'hspg2': 277,
 'cela3b': 278,
 'cela3a': 279,
 'cdc42': 280,
 'wnt4': 281,
 'zbtb40': 282,
 'epha8': 283,
 'c1qa': 284,
 'c1qc': 285,
 'c1qb': 286,
 'ephb2': 287,
 'lactbl1': 288,
 'tex46': 289,
 'kdm1a': 290,
 'luzp1': 291,
 'htr1d': 292,
 'hnrnpr': 293,
 'znf436': 294,
 'tcea3': 295,
 'asap3': 296,
 'e2f2': 297,
 'id3': 298,
 'rpl11': 299,
 'eloa': 300,
 'pithd1': 301,
 'lypla2': 302,
 'gale': 303,
 'hmgcl': 304,
 'fuca1': 305,
 'cnr2': 306,
 'pnrc2': 307,
 'srsf10': 308,
 'myom3': 309,
 'il22ra1': 310,
 'ifnlr1': 311,
 'grhl3': 312,
 'stpg1': 313,
 'nipal3': 314,
 'rcan3': 315,
 'ncmap': 316,
 'srrm1': 317,
 'clic4': 318,
 'runx3': 319,
 'syf2': 320,
 'rsrp1': 321,
 'rhd': 322,
 'tmem50a': 323,
 'rhce': 324,
 'maco1': 325,
 'ldlrap1': 326,
 'man1c1': 327,
 'selenon': 328,
 'mtfr1l': 329,
 'aunip': 330,
 'paqr7': 331,
 'stmn1': 332,
 'pafah2': 333,
 'extl1': 334,
 'slc30a2': 335,
 'trim63': 336,
 'pdik1l': 337,
 'fam110d': 338,
 'c1orf232': 339,
 'znf593os': 340,
 'znf593': 341,
 'cnksr1': 342,
 'catsper4': 343,
 'cep85': 344,
 'sh3bgrl3': 345,
 'ubxn11': 346,
 'cd52': 347,
 'crybg2': 348,
 'znf683': 349,
 'lin28a': 350,
 'dhdds': 351,
 'hmgn2': 352,
 'rps6ka1': 353,
 'arid1a': 354,
 'pigv': 355,
 'zdhhc18': 356,
 'sfn': 357,
 'gpn2': 358,
 'gpatch3': 359,
 'nudc': 360,
 'nr0b2': 361,
 'kdf1': 362,
 'trnp1': 363,
 'tent5b': 364,
 'slc9a1': 365,
 'wdtc1': 366,
 'tmem222': 367,
 'sytl1': 368,
 'map3k6': 369,
 'fcn3': 370,
 'cd164l2': 371,
 'gpr3': 372,
 'wasf2': 373,
 'ahdc1': 374,
 'fgr': 375,
 'ifi6': 376,
 'fam76a': 377,
 'stx12': 378,
 'ppp1r8': 379,
 'themis2': 380,
 'rpa2': 381,
 'smpdl3b': 382,
 'xkr8': 383,
 'eya3': 384,
 'ptafr': 385,
 'dnajc8': 386,
 'atp5if1': 387,
 'sesn2': 388,
 'med18': 389,
 'phactr4': 390,
 'rcc1': 391,
 'trnau1ap': 392,
 'taf12': 393,
 'rab42': 394,
 'gmeb1': 395,
 'ythdf2': 396,
 'oprd1': 397,
 'epb41': 398,
 'tmem200b': 399,
 'srsf4': 400,
 'mecr': 401,
 'ptpru': 402,
 'matn1': 403,
 'laptm5': 404,
 'sdc3': 405,
 'pum1': 406,
 'nkain1': 407,
 'snrnp40': 408,
 'zcchc17': 409,
 'fabp3': 410,
 'serinc2': 411,
 'tinagl1': 412,
 'hcrtr1': 413,
 'pef1': 414,
 'col16a1': 415,
 'adgrb2': 416,
 'spocd1': 417,
 'ptp4a2': 418,
 'khdrbs1': 419,
 'tmem39b': 420,
 'kpna6': 421,
 'txlna': 422,
 'ccdc28b': 423,
 'iqcc': 424,
 'dcdc2b': 425,
 'tmem234': 426,
 'eif3i': 427,
 'fam167b': 428,
 'lck': 429,
 'hdac1': 430,
 'marcksl1': 431,
 'tssk3': 432,
 'fam229a': 433,
 'bsdc1': 434,
 'zbtb8b': 435,
 'zbtb8a': 436,
 'zbtb8os': 437,
 'rbbp4': 438,
 'sync': 439,
 'kiaa1522': 440,
 'yars1': 441,
 's100pbp': 442,
 'fndc5': 443,
 'hpca': 444,
 'tmem54': 445,
 'rnf19b': 446,
 'ak2': 447,
 'azin2': 448,
 'trim62': 449,
 'znf362': 450,
 'a3galt2': 451,
 'phc2': 452,
 'zscan20': 453,
 'csmd2': 454,
 'hmgb4': 455,
 'c1orf94': 456,
 'smim12': 457,
 'gjb5': 458,
 'gjb4': 459,
 'gjb3': 460,
 'gja4': 461,
 'dlgap3': 462,
 'tmem35b': 463,
 'zmym6': 464,
 'zmym1': 465,
 'sfpq': 466,
 'zmym4': 467,
 'kiaa0319l': 468,
 'ncdn': 469,
 'tfap2e': 470,
 'psmb2': 471,
 'c1orf216': 472,
 'clspn': 473,
 'ago4': 474,
 'ago1': 475,
 'ago3': 476,
 'tekt2': 477,
 'adprs': 478,
 'col8a2': 479,
 'trappc3': 480,
 'map7d1': 481,
 'thrap3': 482,
 'sh3d21': 483,
 'eva1b': 484,
 'stk40': 485,
 'lsm10': 486,
 'oscp1': 487,
 'mrps15': 488,
 'csf3r': 489,
 'grik3': 490,
 'zc3h12a': 491,
 'meaf6': 492,
 'snip1': 493,
 'dnali1': 494,
 'gnl2': 495,
 'rspo1': 496,
 'c1orf109': 497,
 'cdca8': 498,
 'epha10': 499,
 'maneal': 500,
 'yrdc': 501,
 'c1orf122': 502,
 'mtf1': 503,
 'inpp5b': 504,
 'sf3a3': 505,
 'fhl3': 506,
 'utp11': 507,
 'pou3f1': 508,
 'rragc': 509,
 'mycbp': 510,
 'gja9': 511,
 'rhbdl2': 512,
 'akirin1': 513,
 'ndufs5': 514,
 'macf1': 515,
 'bmp8a': 516,
 'pabpc4': 517,
 'heyl': 518,
 'nt5c1a': 519,
 'hpcal4': 520,
 'ppie': 521,
 'bmp8b': 522,
 'oxct2': 523,
 'trit1': 524,
 'mycl': 525,
 'mfsd2a': 526,
 'cap1': 527,
 'ppt1': 528,
 'rlf': 529,
 'tmco2': 530,
 'zmpste24': 531,
 'col9a2': 532,
 'smap2': 533,
 'zfp69b': 534,
 'zfp69': 535,
 'exo5': 536,
 'znf684': 537,
 'rims3': 538,
 'nfyc': 539,
 'kcnq4': 540,
 'cited4': 541,
 'ctps1': 542,
 'slfnl1': 543,
 'scmh1': 544,
 'foxo6': 545,
 'edn2': 546,
 'hivep3': 547,
 'guca2b': 548,
 'guca2a': 549,
 'foxj3': 550,
 'rimkla': 551,
 'zmynd12': 552,
 'ppcs': 553,
 'ccdc30': 554,
 'ppih': 555,
 'ybx1': 556,
 'cldn19': 557,
 'p3h1': 558,
 'c1orf50': 559,
 'tmem269': 560,
 'svbp': 561,
 'ermap': 562,
 'znf691': 563,
 'slc2a1': 564,
 'fam183a': 565,
 'ebna1bp2': 566,
 'cfap57': 567,
 'tmem125': 568,
 'c1orf210': 569,
 'tie1': 570,
 'mpl': 571,
 'cdc20': 572,
 'elovl1': 573,
 'med8': 574,
 'szt2': 575,
 'hyi': 576,
 'ptprf': 577,
 'kdm4a': 578,
 'st3gal3': 579,
 'artn': 580,
 'ipo13': 581,
 'dph2': 582,
 'atp6v0b': 583,
 'b4galt2': 584,
 'ccdc24': 585,
 'slc6a9': 586,
 'klf17': 587,
 'klf18': 588,
 'dmap1': 589,
 'eri3': 590,
 'rnf220': 591,
 'tmem53': 592,
 'armh1': 593,
 'kif2c': 594,
 'rps8': 595,
 'best4': 596,
 'plk3': 597,
 'dynlt4': 598,
 'btbd19': 599,
 'ptch2': 600,
 'eif2b3': 601,
 'hectd3': 602,
 'urod': 603,
 'zswim5': 604,
 'hpdl': 605,
 'mutyh': 606,
 'toe1': 607,
 'tesk2': 608,
 'ccdc163': 609,
 'mmachc': 610,
 'prdx1': 611,
 'akr1a1': 612,
 'nasp': 613,
 'ccdc17': 614,
 'gpbp1l1': 615,
 'tmem69': 616,
 'ipp': 617,
 'mast2': 618,
 'pik3r3': 619,
 'tspan1': 620,
 'p3r3urf': 621,
 'pomgnt1': 622,
 'lurap1': 623,
 'rad54l': 624,
 'lrrc41': 625,
 'uqcrh': 626,
 'nsun4': 627,
 'faah': 628,
 'dmbx1': 629,
 'tmem275': 630,
 'kncn': 631,
 'mknk1': 632,
 'mob3c': 633,
 'atpaf1': 634,
 'tex38': 635,
 'efcab14': 636,
 'cyp4b1': 637,
 'cyp4a11': 638,
 'cyp4x1': 639,
 'cyp4z1': 640,
 'cyp4a22': 641,
 'pdzk1ip1': 642,
 'tal1': 643,
 'stil': 644,
 'cmpk1': 645,
 'foxe3': 646,
 'foxd2': 647,
 'trabd2b': 648,
 'slc5a9': 649,
 'spata6': 650,
 'agbl4': 651,
 'bend5': 652,
 'elavl4': 653,
 'dmrta2': 654,
 'faf1': 655,
 'cdkn2c': 656,
 'c1orf185': 657,
 'rnf11': 658,
 'ttc39a': 659,
 'eps15': 660,
 'osbpl9': 661,
 'nrdc': 662,
 'rab3b': 663,
 'txndc12': 664,
 'kti12': 665,
 'btf3l4': 666,
 'zfyve9': 667,
 'cc2d1b': 668,
 'orc1': 669,
 'prpf38a': 670,
 'tut4': 671,
 'gpx7': 672,
 'shisal2a': 673,
 'coa7': 674,
 'zyg11b': 675,
 'zyg11a': 676,
 'echdc2': 677,
 'scp2': 678,
 'podn': 679,
 'slc1a7': 680,
 'cpt2': 681,
 'czib': 682,
 'magoh': 683,
 'lrp8': 684,
 'dmrtb1': 685,
 'glis1': 686,
 'ndc1': 687,
 'yipf1': 688,
 'dio1': 689,
 'hspb11': 690,
 'lrrc42': 691,
 'ldlrad1': 692,
 'tmem59': 693,
 'tceanc2': 694,
 'cdcp2': 695,
 'cyb5rl': 696,
 'mrpl37': 697,
 'ssbp3': 698,
 'acot11': 699,
 'fam151a': 700,
 'mroh7': 701,
 'ttc4': 702,
 'pars2': 703,
 'ttc22': 704,
 'lexm': 705,
 'dhcr24': 706,
 'tmem61': 707,
 'bsnd': 708,
 'pcsk9': 709,
 'usp24': 710,
 'plpp3': 711,
 'prkaa2': 712,
 'fyb2': 713,
 'c8a': 714,
 'c8b': 715,
 'dab1': 716,
 'oma1': 717,
 'tacstd2': 718,
 'mysm1': 719,
 'jun': 720,
 'fggy': 721,
 'hook1': 722,
 'cyp2j2': 723,
 'c1orf87': 724,
 'nfia': 725,
 'tm2d1': 726,
 'patj': 727,
 'l1td1': 728,
 'kank4': 729,
 'usp1': 730,
 'dock7': 731,
 'angptl3': 732,
 'atg4c': 733,
 'foxd3': 734,
 'alg6': 735,
 'itgb3bp': 736,
 'efcab7': 737,
 'pgm1': 738,
 'ror1': 739,
 'ube2u': 740,
 'cachd1': 741,
 'raver2': 742,
 'jak1': 743,
 'ak4': 744,
 'dnajc6': 745,
 'leprot': 746,
 'lepr': 747,
 'pde4b': 748,
 'sgip1': 749,
 'dynlt5': 750,
 'insl5': 751,
 'dnai4': 752,
 'mier1': 753,
 'slc35d1': 754,
 'c1orf141': 755,
 'il23r': 756,
 'il12rb2': 757,
 'serbp1': 758,
 'gadd45a': 759,
 'gng12': 760,
 'diras3': 761,
 'wls': 762,
 'rpe65': 763,
 'depdc1': 764,
 'lrrc7': 765,
 'lrrc40': 766,
 'srsf11': 767,
 'ankrd13c': 768,
 'cth': 769,
 'ptger3': 770,
 'zranb2': 771,
 'negr1': 772,
 'lrriq3': 773,
 'fpgt': 774,
 'tnni3k': 775,
 'lrrc53': 776,
 'erich3': 777,
 'cryz': 778,
 'tyw3': 779,
 'lhx8': 780,
 'slc44a5': 781,
 'acadm': 782,
 'rabggtb': 783,
 'msh4': 784,
 'asb17': 785,
 'st6galnac3': 786,
 'st6galnac5': 787,
 'pigk': 788,
 'ak5': 789,
 'zzz3': 790,
 'usp33': 791,
 'miga1': 792,
 'nexn': 793,
 'fubp1': 794,
 'dnajb4': 795,
 'gipc2': 796,
 'ptgfr': 797,
 'ifi44l': 798,
 'ifi44': 799,
 'adgrl4': 800,
 'adgrl2': 801,
 'ttll7': 802,
 'prkacb': 803,
 'samd13': 804,
 'dnase2b': 805,
 'rpf1': 806,
 'gng5': 807,
 'spata1': 808,
 'ctbs': 809,
 'ssx2ip': 810,
 'lpar3': 811,
 'mcoln2': 812,
 'dnai3': 813,
 'mcoln3': 814,
 'syde2': 815,
 'c1orf52': 816,
 'bcl10': 817,
 'ddah1': 818,
 'ccn1': 819,
 'znhit6': 820,
 'col24a1': 821,
 'odf2l': 822,
 'clca2': 823,
 'clca1': 824,
 'clca4': 825,
 'sh3glb1': 826,
 'selenof': 827,
 'hs2st1': 828,
 'lmo4': 829,
 'pkn2': 830,
 'gtf2b': 831,
 'kyat3': 832,
 'rbmxl1': 833,
 'gbp3': 834,
 'gbp1': 835,
 'gbp2': 836,
 'gbp7': 837,
 'gbp4': 838,
 'gbp5': 839,
 'gbp6': 840,
 'lrrc8b': 841,
 'lrrc8c': 842,
 'lrrc8d': 843,
 'znf326': 844,
 'barhl2': 845,
 'znf644': 846,
 'hfm1': 847,
 'cdc7': 848,
 'tgfbr3': 849,
 'brdt': 850,
 'ephx4': 851,
 'setsip': 852,
 'btbd8': 853,
 'c1orf146': 854,
 'glmn': 855,
 'rpap2': 856,
 'gfi1': 857,
 'evi5': 858,
 'rpl5': 859,
 'dipk1a': 860,
 'mtf2': 861,
 'tmed5': 862,
 'ccdc18': 863,
 'dr1': 864,
 'fnbp1l': 865,
 'bcar3': 866,
 'dnttip2': 867,
 'gclm': 868,
 'abca4': 869,
 'arhgap29': 870,
 'abcd3': 871,
 'f3': 872,
 'slc44a3': 873,
 'cnn3': 874,
 'alg14': 875,
 'tlcd4': 876,
 'rwdd3': 877,
 'ptbp2': 878,
 'dpyd': 879,
 'snx7': 880,
 'plppr5': 881,
 'plppr4': 882,
 'palmd': 883,
 'frrs1': 884,
 'agl': 885,
 'slc35a3': 886,
 'mfsd14a': 887,
 'sass6': 888,
 'trmt13': 889,
 'lrrc39': 890,
 'dbt': 891,
 'rtca': 892,
 'cdc14a': 893,
 'gpr88': 894,
 'vcam1': 895,
 'extl2': 896,
 'slc30a7': 897,
 'dph5': 898,
 's1pr1': 899,
 'olfm3': 900,
 'col11a1': 901,
 'rnpc3': 902,
 'amy2b': 903,
 'amy2a': 904,
 'amy1a': 905,
 'amy1b': 906,
 'amy1c': 907,
 'prmt6': 908,
 'ntng1': 909,
 'vav3': 910,
 'slc25a24': 911,
 'nbpf4': 912,
 'nbpf6': 913,
 'fam102b': 914,
 'henmt1': 915,
 'prpf38b': 916,
 'fndc7': 917,
 'stxbp3': 918,
 'aknad1': 919,
 'gpsm2': 920,
 'clcc1': 921,
 'wdr47': 922,
 'taf13': 923,
 'tmem167b': 924,
 'c1orf194': 925,
 'elapor1': 926,
 'sars1': 927,
 'celsr2': 928,
 'psrc1': 929,
 'mybphl': 930,
 'sort1': 931,
 'psma5': 932,
 'sypl2': 933,
 'atxn7l2': 934,
 'cyb561d1': 935,
 'amigo1': 936,
 'gpr61': 937,
 'gnai3': 938,
 'gnat2': 939,
 'ampd2': 940,
 'gstm4': 941,
 'gstm2': 942,
 'gstm1': 943,
 'gstm5': 944,
 'gstm3': 945,
 'eps8l3': 946,
 'csf1': 947,
 'ahcyl1': 948,
 'strip1': 949,
 'alx3': 950,
 'ubl4b': 951,
 'slc6a17': 952,
 'kcnc4': 953,
 'rbm15': 954,
 'slc16a4': 955,
 'lamtor5': 956,
 'prok1': 957,
 'kcna10': 958,
 'kcna2': 959,
 'kcna3': 960,
 'cd53': 961,
 'lrif1': 962,
 'dram2': 963,
 'cept1': 964,
 'dennd2d': 965,
 'chi3l2': 966,
 'chia': 967,
 'pifo': 968,
 'ovgp1': 969,
 'wdr77': 970,
 'atp5pb': 971,
 'c1orf162': 972,
 'tmigd3': 973,
 'adora3': 974,
 'rap1a': 975,
 'inka2': 976,
 'ddx20': 977,
 'kcnd3': 978,
 'cttnbp2nl': 979,
 'wnt2b': 980,
 'st7l': 981,
 'capza1': 982,
 'mov10': 983,
 'rhoc': 984,
 'ppm1j': 985,
 'tafa3': 986,
 'slc16a1': 987,
 'lrig2': 988,
 'magi3': 989,
 'phtf1': 990,
 'rsbn1': 991,
 'ptpn22': 992,
 'bcl2l15': 993,
 'ap4b1': 994,
 'dclre1b': 995,
 'hipk1': 996,
 'olfml3': 997,
 'syt6': 998,
 'trim33': 999,
 ...}

In [12]:
only_in_all_genes = all_genes_set - adata_genes_set

only_in_adata_genes = adata_genes_set - all_genes_set

# 输出结果
print(f"仅在 all_genes 中存在的基因数量: {len(only_in_all_genes)}")
print(f"仅在 all_genes 中存在的基因: {only_in_all_genes}")

print(f"仅在 adata_genes 中存在的基因数量: {len(only_in_adata_genes)}")
print(f"仅在 adata_genes 中存在的基因: {only_in_adata_genes}")

仅在 all_genes 中存在的基因数量: 6257

In [13]:
import numpy as np
from scipy.sparse import csr_matrix

# Initialize a mapping from gene names in adata to their column indices
adata_gene_to_index = {gene: idx for idx, gene in enumerate(adata_genes_lower)}

# Create an array to map adata.X column indices to new_data column indices
adata_to_new_data_indices = -1 * np.ones(adata.X.shape[1], dtype=int)
for idx, gene in enumerate(adata_genes_lower):
    if gene in gene_to_index:
        adata_to_new_data_indices[idx] = gene_to_index[gene]

In [14]:

# Extract data from adata.X without converting it to a dense array
data = adata.X.data
indices = adata.X.indices
indptr = adata.X.indptr

# Map the column indices to the new indices in new_data
mapped_indices = adata_to_new_data_indices[indices]

# Filter out entries where the mapping is invalid (-1)
valid_entries = mapped_indices != -1
new_data_values = data[valid_entries]
new_data_indices = mapped_indices[valid_entries]

# Build the new indptr array for the new_data matrix
new_indptr = np.zeros(adata.X.shape[0] + 1, dtype=int)

In [15]:
for i in range(adata.X.shape[0]):
    row_start = indptr[i]
    row_end = indptr[i + 1]
    valid_count = np.sum(valid_entries[row_start:row_end])
    new_indptr[i + 1] = new_indptr[i] + valid_count

In [16]:
# Construct the new_data sparse matrix
new_data = csr_matrix(
    (new_data_values, new_data_indices, new_indptr),
    shape=(adata.X.shape[0], len(all_genes)),
    dtype=np.float32
)

In [17]:
new_data = new_data.toarray()

In [18]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.model_selection import train_test_split


label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(adata.obs['cell_type'])  # 预先编码标签


random_seed = 42
X_train_val, X_test, y_train_val, y_test = train_test_split(
    new_data, labels_encoded, test_size=0.15, random_state=random_seed)


X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.1765, random_state=random_seed)  # 0.1765 是为了让验证集占 15%

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

estim.model.eval()
with torch.no_grad():
    X_train_tensor = torch.tensor(X_train).float().to(device)
    X_test_tensor = torch.tensor(X_test).float().to(device)
    train_embeddings = estim.model.encoder(X_train_tensor).detach().cpu().numpy()
    test_embeddings = estim.model.encoder(X_test_tensor).detach().cpu().numpy()

cuda

In [19]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

    

    # 初始化和训练KNN分类器
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_embeddings, y_train)
    
    # 模型预测
predictions = knn.predict(test_embeddings)

    # 计算准确率和 F1 分数
accuracy = accuracy_score(y_test, predictions)
print(f"KNN Accuracy on Test Data: {accuracy}")
f1 = f1_score(y_test, predictions, average='weighted')
print(f"Weighted F1 Score: {f1}")
    
macro_f1 = f1_score(y_test, predictions, average='macro')
print(f'Macro F1 Score: {macro_f1}')

    # 计算随机猜测的准确率
class_probabilities = np.bincount(y_test) / len(y_test)
random_accuracy = np.sum(class_probabilities ** 2)
print(f"Random Guess Accuracy: {random_accuracy}")

    # 生成分类报告
report = classification_report(y_test, predictions, target_names=label_encoder.classes_)
print(report)

KNN Accuracy on Test Data: 0.46086991510079267
Weighted F1 Score: 0.4311292862890625
Macro F1 Score: 0.17269234444250775
Random Guess Accuracy: 0.2526864384339867
                                                           precision    recall  f1-score   support

                          blood vessel smooth muscle cell       0.14      0.09      0.11       483
                                         endothelial cell       0.40      0.52      0.46      7705
                 kidney collecting duct intercalated cell       0.10      0.01      0.03        68
                    kidney collecting duct principal cell       0.10      0.02      0.03       376
          kidney distal convoluted tubule epithelial cell       0.58      0.18      0.27       509
                                     kidney granular cell       0.00      0.00      0.00        21
                           kidney interstitial fibroblast       0.28      0.04      0.07       270
kidney loop of Henle thick ascending limb epithelial cell       0.60      0.56      0.58      2014
        kidney proximal convoluted tubule epithelial cell       0.55      0.66      0.60      8716
                                                leukocyte       0.23      0.11      0.15      3956
                                               macrophage       0.06      0.01      0.01       552
                             macula densa epithelial cell       0.00      0.00      0.00        19
                                           mesangial cell       0.50      0.03      0.06        31
                                                 podocyte       0.24      0.03      0.05       133

                                                 accuracy                           0.46     24853
                                                macro avg       0.27      0.16      0.17     24853
                                             weighted avg       0.43      0.46      0.43     24853

/home/hanchuangyi/miniconda3/envs/ssl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hanchuangyi/miniconda3/envs/ssl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hanchuangyi/miniconda3/envs/ssl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [20]:

import pandas as pd
import os
import re

# 当前 Notebook 文件名
notebook_name = "slide_seq_mouse_kidney_random_mask_zero_shot_42.ipynb"

# 初始化需要打印的值
init_train_loss = train_losses[0] if 'train_losses' in globals() else None
init_val_loss = val_losses[0] if 'val_losses' in globals() else None
converged_epoch = len(train_losses) - patience if 'train_losses' in globals() else None
converged_val_loss = best_val_loss if 'best_val_loss' in globals() else None

# 打印所有所需的指标
print("Metrics Summary:")
if 'train_losses' in globals():
    print(f"init_train_loss\tinit_val_loss\tconverged_epoch\tconverged_val_loss\tmacro_f1\tweighted_f1\tmicor_f1")
    print(f"{init_train_loss:.3f}\t{init_val_loss:.3f}\t{converged_epoch}\t{converged_val_loss:.3f}\t{macro_f1:.3f}\t{f1:.3f}\t{accuracy:.3f}")
else:
    print(f"macro_f1\tweighted_f1\tmicor_f1")
    print(f"{macro_f1:.3f}\t{f1:.3f}\t{accuracy:.3f}")

# 保存结果到 CSV 文件
output_data = {
    'dataset_split_random_seed': [int(random_seed)],
    'dataset': ['slide_seq_mouse_kidney'],
    'method': [re.search(r'kidney_(.*?)_\d+', notebook_name).group(1)],
    'init_train_loss': [init_train_loss if init_train_loss is not None else ''],
    'init_val_loss': [init_val_loss if init_val_loss is not None else ''],
    'converged_epoch': [converged_epoch if converged_epoch is not None else ''],
    'converged_val_loss': [converged_val_loss if converged_val_loss is not None else ''],
    'macro_f1': [macro_f1],
    'weighted_f1': [f1],
    'micor_f1': [accuracy]
}
output_df = pd.DataFrame(output_data)

# 保存到当前目录下名为 results 的文件夹中
if not os.path.exists('results'):
    os.makedirs('results')

csv_filename = f"results/{os.path.splitext(notebook_name)[0]}_results.csv"
output_df.to_csv(csv_filename, index=False)

Metrics Summary:
macro_f1	weighted_f1	micor_f1
0.173	0.431	0.461