In [2]:
import scanpy as sc

In [48]:
filtered.write_h5ad('../dataset/GEX_human_neocortex_SSL.h5ad')

In [17]:
sampled

AnnData object with n_obs × n_vars = 130906 × 32480
    obs: 'dataset', 'Group', 'sex', 'Region', 'class', 'subclass', 'type', 'Estimated_postconceptional_age_in_days', 'nCount_RNA', 'nFeature_RNA', 'nucleosome_signal', 'TSS.enrichment', 'SCR_score', 'cell_type'
    var: 'tmp'
    obsm: 'SSL_BT_FT', 'SSL_BT_ZS', 'SSL_GP_FT', 'SSL_GP_ZS', 'SSL_RM_FT', 'SSL_RM_ZS', 'scVI', 'supervised', 'umap'

In [ ]:
three_region = adata[adata.obs['Region'].isin(['BA10','BA17','PFC'])]

View of AnnData object with n_obs × n_vars = 131474 × 32480
    obs: 'dataset', 'Group', 'sex', 'Region', 'class', 'subclass', 'type', 'Estimated_postconceptional_age_in_days', 'nCount_RNA', 'nFeature_RNA', 'nucleosome_signal', 'TSS.enrichment', 'SCR_score', 'type_updated', 'donor_id'
    var: 'id', 'name'
    obsm: 'umap'

In [ ]:
filtered = three_region[three_region.obs['cell_type'] != 'Unknown']
filtered

View of AnnData object with n_obs × n_vars = 130906 × 32480
    obs: 'dataset', 'Group', 'sex', 'Region', 'class', 'subclass', 'type', 'Estimated_postconceptional_age_in_days', 'nCount_RNA', 'nFeature_RNA', 'nucleosome_signal', 'TSS.enrichment', 'SCR_score', 'type_updated', 'donor_id', 'cell_type'
    var: 'id', 'name'
    obsm: 'umap'

In [35]:
filtered.X

<Compressed Sparse Column sparse matrix of dtype 'float32'
	with 325339953 stored elements and shape (130906, 32480)>

In [43]:
print(filtered.raw.X)

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 364295744 stored elements and shape (130906, 32480)>
  Coords	Values
  (0, 7)	2.0
  (0, 51)	1.0
  (0, 71)	1.0
  (0, 75)	1.0
  (0, 77)	1.0
  (0, 112)	1.0
  (0, 146)	1.0
  (0, 156)	2.0
  (0, 189)	4.0
  (0, 208)	1.0
  (0, 217)	2.0
  (0, 226)	1.0
  (0, 265)	1.0
  (0, 277)	2.0
  (0, 345)	2.0
  (0, 346)	1.0
  (0, 361)	1.0
  (0, 372)	1.0
  (0, 398)	4.0
  (0, 420)	1.0
  (0, 425)	1.0
  (0, 429)	2.0
  (0, 435)	1.0
  (0, 446)	3.0
  (0, 480)	1.0
  :	:
  (130905, 32247)	2.0
  (130905, 32248)	1.0
  (130905, 32252)	1.0
  (130905, 32257)	2.0
  (130905, 32262)	15.0
  (130905, 32265)	3.0
  (130905, 32270)	7.0
  (130905, 32271)	1.0
  (130905, 32282)	1.0
  (130905, 32295)	7.0
  (130905, 32297)	4.0
  (130905, 32298)	1.0
  (130905, 32303)	1.0
  (130905, 32309)	2.0
  (130905, 32310)	1.0
  (130905, 32311)	2.0
  (130905, 32313)	1.0
  (130905, 32330)	1.0
  (130905, 32348)	1.0
  (130905, 32372)	7.0
  (130905, 32421)	1.0
  (130905, 32451)	1.0
  (130905, 32454)	1.0
  (130905, 32456)	1.0
  (130905, 32463)	1.0

In [42]:
# 假设 filtered 是一个 AnnData 对象
# 首先，确保你有 filtered.var['id'] 列和 filtered.raw
# 然后对原始数据切片，创建新的 AnnData 对象

# 选择需要的变量
filtered_var_ids = filtered.var['id']

# 使用这些变量对 .raw 数据进行过滤
filtered_raw_data = filtered.raw[:, filtered.raw.var['id'].isin(filtered_var_ids)].to_adata()

# 将过滤后的数据赋值给 .raw
filtered.raw = filtered_raw_data

# 检查结果
filtered.raw.var

                         id        name
AL627309.1  ENSG00000238009  AL627309.1
AL627309.3  ENSG00000239945  AL627309.3
AL627309.5  ENSG00000241860  AL627309.5
AL627309.4  ENSG00000241599  AL627309.4
AP006222.2  ENSG00000286448  AP006222.2
...                     ...         ...
AC136616.1  ENSG00000273554  AC136616.1
AC136616.2  ENSG00000277761  AC136616.2
AC023491.2  ENSG00000278633  AC023491.2
AC007325.4  ENSG00000278817  AC007325.4
AC007325.2  ENSG00000277196  AC007325.2

[32480 rows x 2 columns]

In [31]:
unknown = three_region[three_region.obs['type'] == 'Unknown']
unknown.obs

,dataset,Group,sex,Region,class,subclass,type,Estimated_postconceptional_age_in_days,nCount_RNA,nFeature_RNA,nucleosome_signal,TSS.enrichment,SCR_score,type_updated,donor_id,cell_type
ARKFrozen-18-PFC_AACCGCTCAGCTACGT-1,ARKFrozen-18-PFC,Second_trimester,M,PFC,Unknown,Unknown,Unknown,98.0,4853.0,2411,0.823733,3.375845,0.042882,Unknown,ARK14,Unknown
ARKFrozen-18-PFC_AACGCTAGTGCTGTAA-1,ARKFrozen-18-PFC,Second_trimester,M,PFC,Unknown,Unknown,Unknown,98.0,1039.0,700,0.255102,4.738119,0.005688,Unknown,ARK14,Unknown
ARKFrozen-18-PFC_AAGCGAATCGTTTCTG-1,ARKFrozen-18-PFC,Second_trimester,M,PFC,Unknown,Unknown,Unknown,98.0,6760.0,3198,0.757159,4.680854,0.168574,Unknown,ARK14,Unknown
ARKFrozen-18-PFC_AATATCCCAATAGCCC-1,ARKFrozen-18-PFC,Second_trimester,M,PFC,Unknown,Unknown,Unknown,98.0,5516.0,2423,0.853877,3.987980,0.151141,Unknown,ARK14,Unknown
ARKFrozen-18-PFC_AATCATGTCATTTGCT-1,ARKFrozen-18-PFC,Second_trimester,M,PFC,Unknown,Unknown,Unknown,98.0,9367.0,3936,0.613921,4.580773,0.248547,Unknown,ARK14,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NIH-M2837-BA10-2_TGGCTTTGTCATGAGC-1,NIH-M2837-BA10-2,Third_trimester,F,BA10,Unknown,Unknown,Unknown,246.0,5070.0,2833,1.050027,3.477891,0.150474,Unknown,NIH-M2837,Unknown
NIH-M2837-BA10-2_TGGTCCTTCCTGAATA-1,NIH-M2837-BA10-2,Third_trimester,F,BA10,Unknown,Unknown,Unknown,246.0,17099.0,5707,1.104839,3.292190,0.197952,Unknown,NIH-M2837,Unknown
NIH-M2837-BA10-2_TGTGGCCAGCATGTTA-1,NIH-M2837-BA10-2,Third_trimester,F,BA10,Unknown,Unknown,Unknown,246.0,7960.0,3454,1.201446,3.875536,0.240404,Unknown,NIH-M2837,Unknown
NIH-M2837-BA10-2_TGTTACTTCAGCATTA-1,NIH-M2837-BA10-2,Third_trimester,F,BA10,Unknown,Unknown,Unknown,246.0,4560.0,2303,1.042450,3.698174,0.097022,Unknown,NIH-M2837,Unknown
NIH-M2837-BA10-2_TTTCATCAGCAAGATG-1,NIH-M2837-BA10-2,Third_trimester,F,BA10,Unknown,Unknown,Unknown,246.0,3379.0,2004,0.846154,4.395604,0.072449,Unknown,NIH-M2837,Unknown

In [13]:
adata.obs['Region']

ARKFrozen-18-PFC_AAACAGCCAAGGTGCA-1     PFC
ARKFrozen-18-PFC_AAACAGCCAATTGAAG-1     PFC
ARKFrozen-18-PFC_AAACAGCCACTAAATC-1     PFC
ARKFrozen-18-PFC_AAACAGCCAGGTTCAC-1     PFC
ARKFrozen-18-PFC_AAACAGCCATCCATCT-1     PFC
                                       ...
NIH-M2837-BA10-2_TTTGTGTTCATGAAGG-1    BA10
NIH-M2837-BA10-2_TTTGTGTTCATTACAG-1    BA10
NIH-M2837-BA10-2_TTTGTGTTCCCATAAA-1    BA10
NIH-M2837-BA10-2_TTTGTGTTCGCTAAGT-1    BA10
NIH-M2837-BA10-2_TTTGTTGGTTTAGTCC-1    BA10
Name: Region, Length: 232328, dtype: category
Categories (8, object): ['BA9', 'BA10', 'BA17', 'Cortex', 'Forebrain', 'PFC', 'Telencephalon', 'V1']

In [5]:
import scanpy as sc
data_path = '../dataset/Chromium_FFPE_Human_Breast_Cancer_Chromium_FFPE_Human_Breast_Cancer_count_sample_filtered_feature_bc_matrix.h5'
sc_data = sc.read_10x_h5(data_path)
sc_data.X = sc_data.X.toarray()

/home/hanchuangyi/miniconda3/envs/envi/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/hanchuangyi/miniconda3/envs/envi/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [6]:
st_data_path = '../dataset/Xenium_breast_cancer_sample1_replicate1.h5ad'
st_data = sc.read_h5ad(st_data_path)
st_data

AnnData object with n_obs × n_vars = 167780 × 313
    obs: 'cell_type', 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area'
    var: 'gene_ids', 'feature_types', 'genome'
    obsm: 'spatial'

In [8]:
# 检查 sc_data.var_names 是否有重复项
duplicates = sc_data.var_names[sc_data.var_names.duplicated()]
print(f"重复的基因: {duplicates}")
# 删除 sc_data.var_names 中的重复基因
sc_data = sc_data[:, ~sc_data.var_names.duplicated()]

重复的基因: Index(['TBCE', 'HSPA14', 'TMSB15B'], dtype='object')

In [16]:
st_data.X = st_data.X.toarray()

In [17]:
import scenvi

envi_model = scenvi.ENVI(spatial_data = st_data, sc_data = sc_data)

Computing Niche Covariance Matrices

/home/hanchuangyi/miniconda3/envs/envi/lib/python3.10/site-packages/scenvi/utils.py:286: ImplicitModificationWarning: Setting element `.layers['log']` of view, initializing view as actual.
  spatial_data.layers["log"] = np.log(spatial_data.X + 1)

Initializing CVAE
Finished Initializing ENVI

In [18]:
import os

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0" # Change to -1 if you want to use CPU!

import warnings
warnings.filterwarnings('ignore')

In [19]:
envi_model.train()

 spatial: -5.429e-01 sc: -3.583e-01 cov: -3.041e-03 kl: 5.710e-01: 100%|██████████| 16000/16000 [02:18<00:00, 115.60it/s]

In [20]:
envi_model.impute_genes()

Finished imputing missing gene for spatial data! See 'imputation' in obsm of ENVI.spatial_data

In [21]:
st_data.uns['COVET_genes'] =  envi_model.CovGenes
st_data.obsm['imputation'] = envi_model.spatial_data.obsm['imputation']

In [23]:
st_data.uns['COVET_genes']
st_data.obsm['imputation']

,ABCC11,ACTA2,ACTG2,ADAM9,ADGRE5,ADH1B,ADIPOQ,AGR3,AHSP,AIF1,...,ACKR2,ZBBX,DSCC1,TMEM179,STS,ADAMTS18,KRT77,CD36,COL1A1,ST3GAL4
1,0.028160,0.000295,0.000415,0.025097,0.002433,0.000147,0.000306,0.006388,0.000428,0.000165,...,0.021123,0.000037,0.001331,0.000170,0.014910,0.002856,0.013825,0.001115,0.002072,0.006893
2,0.135054,0.001385,0.001473,0.068828,0.004031,0.000012,0.000023,0.172641,0.000670,0.000663,...,0.066992,0.000361,0.015996,0.000026,0.047513,0.006917,0.008223,0.000363,0.008414,0.116683
3,0.007224,0.000055,0.000029,0.002296,0.004618,0.000019,0.000180,0.000455,0.000338,0.000170,...,0.002459,0.000005,0.000496,0.000149,0.003904,0.000574,0.000939,0.001876,0.001330,0.000663
4,0.024370,0.000056,0.000031,0.002436,0.005237,0.000038,0.000413,0.000782,0.000201,0.000105,...,0.002064,0.000007,0.000552,0.000059,0.004327,0.000366,0.000710,0.001102,0.000917,0.001066
5,0.009818,0.000823,0.000448,0.065065,0.008251,0.000099,0.000052,0.026091,0.000656,0.003703,...,0.018674,0.000026,0.005910,0.000052,0.011775,0.004768,0.002264,0.009819,0.061971,0.019700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167776,0.778266,0.060839,0.006891,0.256100,0.057417,0.000132,0.000247,1.535778,0.000267,0.808343,...,0.448367,0.000248,0.174384,0.000045,0.092180,0.077322,0.000573,0.081221,1.406556,1.383145
167777,0.143625,0.021503,0.014047,0.023827,0.002350,0.000042,0.000114,0.673644,0.000323,0.000649,...,0.059325,0.000069,0.025449,0.000018,0.033146,0.014673,0.001116,0.000456,0.035410,0.144712
167778,2.403864,0.122796,0.026666,0.723552,0.013546,0.000121,0.001161,3.509130,0.000189,0.002804,...,1.407184,0.000779,0.304455,0.000029,0.211190,0.127005,0.000054,0.003646,1.833772,3.715529
167779,0.721765,0.003447,0.002150,0.074558,0.001467,0.000196,0.000544,1.788613,0.000329,0.001033,...,0.067676,0.000106,0.071447,0.000034,0.070714,0.021477,0.000313,0.000729,0.060874,0.278163
167780,1.552855,0.138159,0.046782,0.452058,0.021138,0.000034,0.000355,4.036428,0.000186,0.014679,...,1.424577,0.000374,0.380852,0.000028,0.169339,0.241315,0.000075,0.002022,2.028858,3.631422

In [ ]:


envi_model.impute_genes()
envi_model.infer_niche_covet()
envi_model.infer_niche_celltype()

st_data.obsm['envi_latent'] = envi_model.spatial_data.obsm['envi_latent']
st_data.obsm['COVET'] = envi_model.spatial_data.obsm['COVET']
st_data.obsm['COVET_SQRT'] = envi_model.spatial_data.obsm['COVET_SQRT']
st_data.obsm['cell_type_niche'] = envi_model.spatial_data.obsm['cell_type_niche']


sc_data.obsm['envi_latent'] = envi_model.sc_data.obsm['envi_latent']
sc_data.uns['COVET_genes'] =  envi_model.CovGenes
sc_data.obsm['COVET'] = envi_model.sc_data.obsm['COVET']
sc_data.obsm['COVET_SQRT'] = envi_model.sc_data.obsm['COVET_SQRT']
sc_data.obsm['cell_type_niche'] = envi_model.sc_data.obsm['cell_type_niche']